package net.pocvpn.client.identity

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM/NoPadding encryptor backed by a non-exportable AndroidKeyStore
 * key. The key never leaves the Keystore - encrypt()/decrypt() only ever
 * hand back plaintext/ciphertext bytes we already had, never the key itself.
 *
 * Key spec: AES, 256-bit, GCM, NoPadding, ENCRYPT+DECRYPT only, generated by
 * this app under a stable alias, randomized IV per encryption.
 */
class AndroidKeystoreAesGcmEncryptor(private val keyAlias: String) : AesGcmKeyEncryptor {

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS = 128
    }

    private val keyStore: KeyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }

    override fun encrypt(plaintext: ByteArray): EncryptedPayload {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val ciphertext = cipher.doFinal(plaintext)
        return EncryptedPayload(iv = cipher.iv, ciphertext = ciphertext)
    }

    override fun decrypt(payload: EncryptedPayload): ByteArray {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            val spec = GCMParameterSpec(GCM_TAG_BITS, payload.iv)
            cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), spec)
            return cipher.doFinal(payload.ciphertext)
        } catch (e: AEADBadTagException) {
            throw IdentityDecryptionFailedException("AEAD authentication failed (wrong/rotated key or tampered data)")
        } catch (e: java.security.GeneralSecurityException) {
            throw IdentityDecryptionFailedException("Keystore key unavailable or cipher error: ${e.javaClass.simpleName}")
        }
    }

    private fun getOrCreateKey(): SecretKey {
        (keyStore.getKey(keyAlias, null) as? SecretKey)?.let { return it }

        val keyGenerator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        val spec = KeyGenParameterSpec.Builder(
            keyAlias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .setRandomizedEncryptionRequired(true)
            .build()
        keyGenerator.init(spec)
        return keyGenerator.generateKey()
    }
}
