package net.pocvpn.client.activation

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.security.MessageDigest
import java.util.Base64

/**
 * B56-4B1 - REAL production-key cross-verification. Proves that the
 * production activation-issuer PUBLIC key committed in
 * [ProductionActivationIssuerTrustAnchors] is the actual counterpart of the
 * real private key generated in the (final, network-isolated) offline
 * ceremony (see `docs/B56_ACTIVATION_ISSUER_KEY_CEREMONY.md`'s "Production
 * ceremony - 2026-09-20 (final, network-isolated)" section), using ONLY the
 * EXISTING, unmodified [ActivationEnvelopeCodec] /
 * [Ed25519ActivationEnvelopeVerifier] / [FixedActivationIssuerTrustAnchors]
 * pipeline - no fixture-only verifier.
 *
 * ## NON_REDEEMABLE PRODUCTION-KEY CROSS-VERIFICATION FIXTURE
 *
 * [SYNTHETIC_ENVELOPE_ARTIFACT_BASE64] below was produced OFFLINE by signing
 * a synthetic [ActivationEnvelope] with the REAL, final production private
 * key (`prod-activation-issuer-2026-09-20-r2`) through the already-reviewed
 * `gateway/tools/activation_envelope_issuer.py` canonical
 * encoding/signing primitives (`canonical_bytes`/`sign_envelope`/
 * `pack_signed_envelope`) - NOT the `issue` command, so
 * `gateway.api.activations.issue_activation()` was never called and no
 * production activation store was ever touched. It is NOT a redeemable
 * production activation:
 *
 * - `activationId`/`credential` are obviously-synthetic fixed test values,
 *   never generated by `issue_activation()`, and were never inserted into
 *   any `activations.json` store.
 * - It carries no bootstrap capability and no bootstrap bundle reference -
 *   no network authority of any kind.
 * - Its signature is public cryptographic output (verifiable by anyone
 *   holding the public key already committed in this same PR), never
 *   private key material.
 *
 * This is the SAME cross-language-compatibility methodology as
 * [ActivationEnvelopePythonCompatibilityTest], applied to the real
 * production key instead of that test's deterministic test-only key.
 */
class ProductionActivationIssuerTrustAnchorsTest {

    private val verifier = Ed25519ActivationEnvelopeVerifier()

    // issuedAt=1_800_000_000_000, expiresAt=+3_600_000ms - verification "now" must fall inside that window.
    private val fixtureNowEpochMillis = 1_800_000_000_000L + 1_800_000L

    @Test
    fun `production key id resolves to exactly 32 public-key bytes`() {
        val anchors = ProductionActivationIssuerTrustAnchors.trustAnchors()
        val publicKey = anchors.publicKeyFor(ActivationIssuerKeyId(ProductionActivationIssuerTrustAnchors.PRIMARY_KEY_ID))
        assertTrue("expected a resolvable production public key", publicKey != null)
        assertEquals(32, publicKey!!.size)
    }

    @Test
    fun `SHA-256 of the committed production public key matches the ceremony fingerprint`() {
        val anchors = ProductionActivationIssuerTrustAnchors.trustAnchors()
        val publicKey = anchors.publicKeyFor(ActivationIssuerKeyId(ProductionActivationIssuerTrustAnchors.PRIMARY_KEY_ID))!!
        val digest = MessageDigest.getInstance("SHA-256").digest(publicKey)
        val fingerprintHex = digest.joinToString("") { "%02x".format(it) }
        assertEquals(CEREMONY_FINGERPRINT_SHA256_HEX, fingerprintHex)
    }

    @Test
    fun `NON_REDEEMABLE PRODUCTION-KEY CROSS-VERIFICATION FIXTURE decodes, verifies, and reports the production issuer key id`() {
        val bytes = Base64.getDecoder().decode(SYNTHETIC_ENVELOPE_ARTIFACT_BASE64)
        val decoded = ActivationEnvelopeCodec.decode(bytes)
        assertTrue("expected successful decode, got $decoded", decoded is SignedActivationEnvelopeDecodeResult.Success)
        val signed = (decoded as SignedActivationEnvelopeDecodeResult.Success).signed

        val anchors = ProductionActivationIssuerTrustAnchors.trustAnchors()
        val result = verifier.verify(signed, anchors, fixtureNowEpochMillis)
        assertTrue("expected the real production-key signature to verify, got $result", result is ActivationEnvelopeVerificationResult.Valid)
        val envelope = (result as ActivationEnvelopeVerificationResult.Valid).envelope

        assertEquals(ProductionActivationIssuerTrustAnchors.PRIMARY_KEY_ID, envelope.issuerKeyId.value)
        assertEquals("b564b100000000000000000000000002", envelope.activationId.value)
        assertEquals("B56_4B1_R2_NON_REDEEMABLE_TEST_CREDENTIAL", envelope.credential.value)
    }

    @Test
    fun `single-byte tampering of the production-key-signed fixture fails signature verification`() {
        val bytes = Base64.getDecoder().decode(SYNTHETIC_ENVELOPE_ARTIFACT_BASE64)
        val tampered = bytes.copyOf()
        // Flip one byte well inside the canonical section, past the fixed
        // header - exercises signature invalidation, not decode-level rejection.
        tampered[40] = (tampered[40].toInt() xor 0x01).toByte()

        val anchors = ProductionActivationIssuerTrustAnchors.trustAnchors()
        val decoded = ActivationEnvelopeCodec.decode(tampered)
        when (decoded) {
            is SignedActivationEnvelopeDecodeResult.Failure -> { /* tampering caught at decode - acceptable */ }
            is SignedActivationEnvelopeDecodeResult.Success -> {
                val result = verifier.verify(decoded.signed, anchors, fixtureNowEpochMillis)
                assertTrue("tampered artifact must not verify as Valid", result is ActivationEnvelopeVerificationResult.Invalid)
                assertEquals(ActivationEnvelopeFailureKind.PACKAGE_SIGNATURE_INVALID, (result as ActivationEnvelopeVerificationResult.Invalid).kind)
            }
        }
    }

    @Test
    fun `manifest trust anchors are not involved in the production activation-issuer anchor`() {
        // Same structural proof as ActivationEnvelopePythonCompatibilityTest -
        // FixedActivationIssuerTrustAnchors (what ProductionActivationIssuerTrustAnchors
        // constructs) does not implement ManifestTrustAnchors at all.
        val manifestTrustAnchorsInterface = Class.forName("net.pocvpn.client.reachability.ManifestTrustAnchors")
        assertFalse(manifestTrustAnchorsInterface.isAssignableFrom(FixedActivationIssuerTrustAnchors::class.java))
        assertFalse(manifestTrustAnchorsInterface.isInstance(ProductionActivationIssuerTrustAnchors.trustAnchors()))
    }

    @Test
    fun `the abandoned first-candidate key id is not present in the production anchor map`() {
        // The first ceremony pass's candidate key (no offline-isolation
        // provenance established) must never appear in the merged trust
        // anchor set - see ProductionActivationIssuerTrustAnchors class docs.
        val anchors = ProductionActivationIssuerTrustAnchors.trustAnchors()
        assertNull(anchors.publicKeyFor(ActivationIssuerKeyId("prod-activation-issuer-2026-09-20")))
    }

    companion object {
        /**
         * From `docs/B56_ACTIVATION_ISSUER_KEY_CEREMONY.md`'s "Production
         * ceremony - 2026-09-20 (final, network-isolated)" section - the
         * real ceremony's own printed fingerprint, recorded out-of-band.
         * Never the private key.
         */
        private const val CEREMONY_FINGERPRINT_SHA256_HEX =
            "88ccf8198af0d7775946253eb958f60f5174c652f6e28a4daecd857ab293e840"

        /**
         * NON_REDEEMABLE PRODUCTION-KEY CROSS-VERIFICATION FIXTURE - see class
         * docs. Signed offline with the real, final production private key
         * (`prod-activation-issuer-2026-09-20-r2`) via
         * `gateway/tools/activation_envelope_issuer.py`'s
         * canonical_bytes/sign_envelope/pack_signed_envelope primitives
         * directly (never `issue`, never `issue_activation()`, never any
         * activation store). activationId/credential are obviously-synthetic
         * fixed test values, not a real redeemable activation.
         */
        private const val SYNTHETIC_ENVELOPE_ARTIFACT_BASE64 =
            "AAAAAQAAAM4AAAAbTk9WQV9BQ1RJVkFUSU9OX0VOVkVMT1BFX1YxAAAAAQAAACBiNTY0YjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMgAAAClCNTZfNEIxX1IyX05PTl9SRURFRU1BQkxFX1RFU1RfQ1JFREVOVElBTAAAAaMYXFAAAAABoxhcUAAAAAGjGJM+gAAAAAAAAAAAABAAAQIDBAUGBwgJCgsMDQ4PAAAAJHByb2QtYWN0aXZhdGlvbi1pc3N1ZXItMjAyNi0wOS0yMC1yMgAAAEA54GayKSVm2ergRoq/ceb9PHB4MSLw+rIW/FUaIFbcm+XxAtJVz9kvQwvtXC5JZR77uDYJrEtMAkgP8mxgCp0A"
    }
}
