#!/usr/bin/env python3
"""B56-4A - operator-only ActivationEnvelope issuer CLI.

This is a SEPARATE tool from gateway/tools/activation_tokens.py (the
existing activation-lifecycle CLI, unchanged and unaffected by this file)
and from gateway/tools/manifest_signing.py (the EXISTING, separate manifest
signing authority). It holds a NEW, delegated activation-issuer Ed25519
private key - never the manifest signing key - and produces a signed
`ActivationEnvelope` (net.pocvpn.client.activation.ActivationEnvelope on the
Android side) that is byte-for-byte compatible with
ActivationEnvelopeCanonicalizer.canonicalBytes()/ActivationEnvelopeCodec.

## Two separate authorities, never crossed

    activation-issuer key  -> ActivationEnvelope   (THIS file)
    manifest signing key   -> EndpointManifest / SignedBootstrapBundle (manifest_signing.py, UNCHANGED)

This tool never signs a manifest, never creates an endpoint fact, never
authorizes a host/IP/port, never uses the manifest private key, and never
adds an activation key to ManifestTrustAnchors. An optional
`--bootstrap-bundle` argument only lets the operator correlate an envelope
with an ALREADY-signed SignedManifest artifact (by exact-byte SHA-256 and
its manifest version) - this tool never re-signs, re-encodes, or modifies
that artifact in any way.

## Existing activation store remains the ONE issuance authority

`issue` calls the EXISTING gateway.api.activations.issue_activation()
directly (imported, never invoked as a subprocess) - activation ID
generation, credential generation/hashing, max_devices, expiry, durable
store locking, and store schema are ALL owned by that module, unchanged.
This file adds a signed envelope wrapper around an activation
issue_activation() already created - it does not reimplement or duplicate
any part of that store.

## issuerKeyId is bound to the private key, never independently typed (PR #95 review fix)

`issue` does NOT accept a free-standing `--issuer-key-id`. It accepts
`--issuer-metadata-file`, the EXACT public-metadata JSON `generate-key`
produced alongside the private key, and requires the public key derived
from `--private-key-file` to match the metadata's own `publicKeyBase64`
byte-for-byte before anything else happens. Without this, an operator
could accidentally sign with private key A while labeling the envelope
`issuerKeyId=B` - a validly-signed envelope no Android trust-anchor
population could ever verify. See `read_issuer_metadata_file` and
`cmd_issue`'s own identity-binding check.

## Private key handling (B12's `--private-key-b64` weakness NOT repeated)

manifest_signing.py's historical `--private-key-b64`/JSON-stdout
`generate-key` pattern is deliberately NOT reused here - see this module's
own `generate-key`/`issue` commands, which accept ONLY `--private-key-file
PATH` (raw 32 Ed25519 private key bytes) and never print, log, or otherwise
surface private key material.

## B56-4A does NOT perform the production ceremony

No production private key is generated by this task, and no production
activation-issuer public key is populated into Android's
FixedActivationIssuerTrustAnchors - see docs/B56_ACTIVATION_ISSUER_KEY_CEREMONY.md.
That is B56-4B, after this tooling is reviewed.

Requires the `cryptography` package (same existing dev-only dependency as
manifest_signing.py - not a gateway API runtime dependency, never imported
by gateway/api/*). Install with: pip install cryptography
"""
from __future__ import annotations

import argparse
import base64
import binascii
import dataclasses
import hashlib
import hmac
import json
import math
import os
import re
import secrets
import stat
import struct
import sys
import tempfile
import time
from typing import Optional, Sequence, Tuple

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_GATEWAY_DIR = os.path.abspath(os.path.join(_THIS_DIR, ".."))
if _GATEWAY_DIR not in sys.path:
    sys.path.insert(0, _GATEWAY_DIR)

from cryptography.hazmat.primitives.asymmetric.ed25519 import (  # noqa: E402
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives import serialization  # noqa: E402

# --- domain/format constants - MUST exactly match the merged Android B56-1 encoding ---

DOMAIN_TAG = "NOVA_ACTIVATION_ENVELOPE_V1"
CANONICAL_FORMAT_VERSION = 1  # ActivationEnvelopeCanonicalizer.FORMAT_VERSION
CODEC_FORMAT_VERSION = 1  # ActivationEnvelopeCodec's outer container FORMAT_VERSION
SIGNATURE_LENGTH = 64
NONCE_LENGTH = 16  # ActivationEnvelope.NONCE_LENGTH
MAX_ENDPOINT_HINTS = 32  # ActivationEnvelope.MAX_ENDPOINT_HINTS
MAX_ENDPOINT_HINT_UTF8_BYTES = 128  # ActivationEnvelope.MAX_ENDPOINT_HINT_UTF8_BYTES
MAX_ISSUER_KEY_ID_UTF8_BYTES = 64  # ActivationIssuerKeyId.MAX_LENGTH_BYTES
MAX_CREDENTIAL_CHARS = 256  # ActivationCredential.MAX_LENGTH
CONTENT_HASH_LENGTH = 32  # ActivationBundleRef.CONTENT_HASH_LENGTH (SHA-256)
PRIVATE_KEY_RAW_BYTES = 32
PUBLIC_KEY_RAW_BYTES = 32

# PR #95 review fix (item 11) - defensive symmetry with the Android side's
# own encoder/decoder bounds (ActivationEnvelopeCanonicalizer.MAX_CANONICAL_BYTES,
# ActivationEnvelopeCodec.MAX_ENCODED_BYTES). This Python encoder must never
# emit an artifact the Android decoder would reject purely for size - these
# are the SAME numbers, never a second, independently-chosen limit, and
# never smaller than Android's own bounds.
MAX_CANONICAL_BYTES = 16_384
MAX_ENCODED_BYTES = 32_768

# Envelope lifetime / activation-expiry sanity bounds - generous but finite,
# so a NaN/Infinity/absurd value can never reach timestamp arithmetic.
_MAX_ENVELOPE_VALID_FOR_HOURS = 24 * 366  # ~1 year
_MAX_ACTIVATION_EXPIRES_IN_DAYS = 366 * 10  # ~10 years

# On POSIX, a private key file must not be group/other readable/writable/
# executable - same "unsafe mode" discipline gateway/api/activations.py's
# own _validate_existing_mode_is_safe already applies to the activation
# store. Windows has no POSIX mode bits at all - see read_private_key_file's
# own truthful platform-limitation note; this mask is never applied there.
_UNSAFE_PRIVATE_KEY_MODE_MASK = 0o077

_ACTIVATION_ID_RE = re.compile(r"^[0-9a-f]{32}$")
_CREDENTIAL_RE = re.compile(r"^[A-Za-z0-9_-]+$")
_FINGERPRINT_RE = re.compile(r"^[0-9a-f]{64}$")

# SignedManifestCodec's own bounds (gateway/tools/manifest_signing.py /
# android SignedManifestCodec.kt) - reused verbatim by
# inspect_signed_manifest_bundle, never a second independently-chosen limit.
_SIGNED_MANIFEST_MAX_CANONICAL_BYTES = 1_000_000
_SIGNED_MANIFEST_MAX_SIGNATURE_BYTES = 256  # SignedManifestCodec's own generic container ceiling

# PR #95 review fix (round 2) - the REAL client trust boundary
# (Ed25519ManifestVerifier) requires an EXACT 64-byte Ed25519 signature;
# this stricter operational bound is enforced by inspect_signed_manifest_bundle
# below (still metadata inspection only - no cryptographic verification).
_SIGNED_MANIFEST_SIGNATURE_LENGTH = 64

# Maximum plausible total SignedManifestCodec container size, derived
# directly from the SAME existing constants above - used to reject an
# obviously over-bound bootstrap-bundle file via a cheap os.path.getsize()
# BEFORE reading it into memory at all (a local DoS/hygiene bound only,
# never a new manifest wire format).
_SIGNED_MANIFEST_MAX_TOTAL_BYTES = 4 + 4 + _SIGNED_MANIFEST_MAX_CANONICAL_BYTES + 4 + _SIGNED_MANIFEST_SIGNATURE_LENGTH

_ISSUER_METADATA_REQUIRED_FIELDS = frozenset({"issuerKeyId", "publicKeyBase64", "publicKeyFingerprintSha256Hex"})


def _activations_module():
    """Lazy import of gateway.api.activations - deferred (rather than a
    top-level import) ONLY so this module's pure encoding/signing/key-
    generation/bundle-inspection logic remains importable and unit-
    testable on a platform without `fcntl` (e.g. Windows dev machines);
    the real gateway.api.activations module itself is unchanged and still
    Linux-only (flock-based locking), matching production reality. This
    is still a direct Python import and call of the EXISTING module -
    never a subprocess invocation of activation_tokens.py."""
    from api import activations as activations_module

    return activations_module


class IssuerError(Exception):
    """A local/operator-input validation or key/file-handling failure - the
    CLI maps this to a loud, non-zero-exit error. Never constructed with,
    or printed alongside, private key or credential material."""


class BundleInspectionError(Exception):
    """The optional --bootstrap-bundle file failed the strict read-only
    outer-container check below - never a trust decision, purely "this
    artifact is not a well-formed SignedManifestCodec container"."""


# --- shared validation helpers - used by BOTH generate-key and issue ---

def validate_issuer_key_id(value: str) -> None:
    """The ONE issuer-key-id validation rule, matching Android's
    ActivationIssuerKeyId contract exactly (PR #95 review fix, item 2):
    not blank/whitespace-only, and its UTF-8 BYTE length (not Python
    `len()`, which counts code points) must not exceed
    MAX_ISSUER_KEY_ID_UTF8_BYTES. Used by generate-key's --key-id AND by
    read_issuer_metadata_file - a single shared helper so the two can
    never drift apart."""
    if not isinstance(value, str) or not value.strip():
        raise IssuerError("issuerKeyId must not be blank or whitespace-only")
    try:
        encoded = value.encode("utf-8")
    except UnicodeEncodeError as exc:
        raise IssuerError(f"issuerKeyId is not valid UTF-8 text: {exc}") from None
    if len(encoded) > MAX_ISSUER_KEY_ID_UTF8_BYTES:
        raise IssuerError(f"issuerKeyId exceeds max UTF-8 byte length ({MAX_ISSUER_KEY_ID_UTF8_BYTES}): {len(encoded)}")


def _utf8_bytes_or_raise(value: str, field_name: str) -> bytes:
    """Encodes `value` as UTF-8, turning a (rare - e.g. a lone surrogate
    from surrogateescape-decoded input) UnicodeEncodeError into a clean
    IssuerError instead of an uncaught traceback (PR #95 review fix, item 3)."""
    try:
        return value.encode("utf-8")
    except UnicodeEncodeError as exc:
        raise IssuerError(f"{field_name} is not valid UTF-8 text: {exc}") from None


# --- ActivationEnvelope canonical encoding - byte-for-byte mirror of ---
# --- ActivationEnvelopeCanonicalizer.kt / ActivationEnvelopeCodec.kt   ---

@dataclasses.dataclass(frozen=True)
class BundleRef:
    manifest_version: int
    content_hash: bytes  # exactly CONTENT_HASH_LENGTH bytes

    def __post_init__(self):
        if self.manifest_version < 1:
            raise IssuerError(f"bundleRef.manifestVersion must be >= 1: {self.manifest_version}")
        if len(self.content_hash) != CONTENT_HASH_LENGTH:
            raise IssuerError(f"bundleRef.contentHash must be exactly {CONTENT_HASH_LENGTH} bytes: {len(self.content_hash)}")


@dataclasses.dataclass(frozen=True)
class ActivationEnvelope:
    activation_id: str
    credential: str
    issued_at_epoch_millis: int
    not_before_epoch_millis: int
    expires_at_epoch_millis: int
    bootstrap_bundle_ref: Optional[BundleRef]
    bootstrap_endpoint_hints: Tuple[str, ...]  # ORDER-PRESERVING - never sorted
    bootstrap_capability_hint: None  # ALWAYS None in B56-4A - see module docs (B56-6 owns this)
    nonce: bytes  # exactly NONCE_LENGTH bytes
    issuer_key_id: str

    def __post_init__(self):
        if not _ACTIVATION_ID_RE.match(self.activation_id):
            raise IssuerError("activationId must be 32 lowercase hex characters")
        if not self.credential:
            raise IssuerError("credential must not be empty")
        if len(self.credential) > MAX_CREDENTIAL_CHARS:
            raise IssuerError(f"credential exceeds max length ({MAX_CREDENTIAL_CHARS})")
        if not _CREDENTIAL_RE.match(self.credential):
            raise IssuerError("credential must be URL-safe base64 (no padding)")
        if self.not_before_epoch_millis >= self.expires_at_epoch_millis:
            raise IssuerError("notBeforeEpochMillis must be before expiresAtEpochMillis")
        if len(self.nonce) != NONCE_LENGTH:
            raise IssuerError(f"nonce must be exactly {NONCE_LENGTH} bytes: {len(self.nonce)}")
        if len(self.bootstrap_endpoint_hints) > MAX_ENDPOINT_HINTS:
            raise IssuerError(f"too many bootstrapEndpointHints ({len(self.bootstrap_endpoint_hints)} > {MAX_ENDPOINT_HINTS})")
        if len(set(self.bootstrap_endpoint_hints)) != len(self.bootstrap_endpoint_hints):
            raise IssuerError("bootstrapEndpointHints contains a duplicate EndpointId")
        for hint in self.bootstrap_endpoint_hints:
            # Matches Android EndpointId's own isNotBlank() contract exactly
            # (PR #95 review fix, item 3) - " " must be rejected here too,
            # not just an empty string.
            if not hint.strip():
                raise IssuerError("bootstrapEndpointHint must not be blank or whitespace-only")
            hint_bytes = _utf8_bytes_or_raise(hint, "bootstrapEndpointHint")
            if len(hint_bytes) > MAX_ENDPOINT_HINT_UTF8_BYTES:
                raise IssuerError(f"bootstrapEndpointHint '{hint}' exceeds max UTF-8 byte length ({MAX_ENDPOINT_HINT_UTF8_BYTES}): {len(hint_bytes)}")
        if self.bootstrap_capability_hint is not None:
            # B56-4A structural rule - see module docs. Not reachable via
            # the CLI (there is no --capability-hint flag), enforced here
            # too so a future programmatic caller cannot silently violate it.
            raise IssuerError("bootstrapCapabilityHint must be None in B56-4A - B56-6 owns this field")
        validate_issuer_key_id(self.issuer_key_id)


def _write_string(buf: bytearray, s: str) -> None:
    b = s.encode("utf-8")
    buf += struct.pack(">i", len(b))
    buf += b


def _write_bytes(buf: bytearray, b: bytes) -> None:
    buf += struct.pack(">i", len(b))
    buf += b


def canonical_bytes(envelope: ActivationEnvelope) -> bytes:
    """MUST stay byte-identical to ActivationEnvelopeCanonicalizer.canonicalBytes
    (Kotlin) - see that file's own field-order comment. If you change one
    side, change the other and re-run the cross-language compatibility
    test (gateway/tools/tests/test_activation_envelope_issuer.py plus
    ActivationEnvelopePythonCompatibilityTest.kt)."""
    buf = bytearray()
    _write_string(buf, DOMAIN_TAG)
    buf += struct.pack(">i", CANONICAL_FORMAT_VERSION)
    _write_string(buf, envelope.activation_id)
    _write_string(buf, envelope.credential)
    buf += struct.pack(">q", envelope.issued_at_epoch_millis)
    buf += struct.pack(">q", envelope.not_before_epoch_millis)
    buf += struct.pack(">q", envelope.expires_at_epoch_millis)

    ref = envelope.bootstrap_bundle_ref
    buf += struct.pack(">?", ref is not None)
    if ref is not None:
        buf += struct.pack(">i", ref.manifest_version)
        _write_bytes(buf, ref.content_hash)

    hints = envelope.bootstrap_endpoint_hints  # ORDER PRESERVED - never sorted
    buf += struct.pack(">i", len(hints))
    for hint in hints:
        _write_string(buf, hint)

    capability = envelope.bootstrap_capability_hint
    buf += struct.pack(">?", capability is not None)
    if capability is not None:
        _write_bytes(buf, capability)

    _write_bytes(buf, envelope.nonce)
    _write_string(buf, envelope.issuer_key_id)
    bytes_out = bytes(buf)
    # PR #95 review fix (item 11) - defensive symmetry: never produce what
    # Android's own decoder would reject purely for size. Every field's own
    # construction-time bound should already make this unreachable; this is
    # a hard backstop, not the primary defense.
    if len(bytes_out) > MAX_CANONICAL_BYTES:
        raise IssuerError(f"canonical envelope encoding exceeds MAX_CANONICAL_BYTES ({MAX_CANONICAL_BYTES}): {len(bytes_out)}")
    return bytes_out


def sign_envelope(envelope: ActivationEnvelope, private_key: Ed25519PrivateKey) -> bytes:
    """Signs ONLY the canonical ActivationEnvelope bytes - never a
    manifest, never a JSON/serialized-object representation."""
    return private_key.sign(canonical_bytes(envelope))


def pack_signed_envelope(canonical: bytes, signature: bytes) -> bytes:
    """The EXACT existing ActivationEnvelopeCodec container shape:
    [formatVersion:i32BE=1][canonicalLength:i32BE][canonicalBytes]
    [signatureLength:i32BE=64][signature]. No alternate format, no JSON
    wrapper, no second envelope wire format."""
    if len(signature) != SIGNATURE_LENGTH:
        raise IssuerError(f"signature must be exactly {SIGNATURE_LENGTH} bytes: {len(signature)}")
    buf = bytearray()
    buf += struct.pack(">i", CODEC_FORMAT_VERSION)
    buf += struct.pack(">i", len(canonical))
    buf += canonical
    buf += struct.pack(">i", len(signature))
    buf += signature
    artifact = bytes(buf)
    # PR #95 review fix (item 11) - same defensive symmetry as canonical_bytes.
    if len(artifact) > MAX_ENCODED_BYTES:
        raise IssuerError(f"encoded envelope artifact exceeds MAX_ENCODED_BYTES ({MAX_ENCODED_BYTES}): {len(artifact)}")
    return artifact


# --- private key file handling - NO CLI secret, ever ---

def read_private_key_file(path: str) -> Ed25519PrivateKey:
    """Reads EXACTLY PRIVATE_KEY_RAW_BYTES (32) raw Ed25519 private key
    bytes from `path`. Never accepts JSON, never accepts Base64 via argv -
    fails closed on wrong length/type/read failure. The key bytes are
    never logged, printed, or included in any exception message this
    function raises.

    PR #95 review fix (item 8) - read-time hygiene, BEFORE the bytes are
    ever used: `path` must be a regular file, and on POSIX its mode must
    not be group/other-accessible (`_UNSAFE_PRIVATE_KEY_MODE_MASK`) - the
    same "refuse an unsafe existing mode" discipline
    gateway/api/activations.py's own store already applies. Windows has no
    POSIX mode bits at all; this check is skipped there and the module's
    own docs/CLI output are truthful about NOT providing an ACL guarantee
    on that platform - never claimed here either.
    """
    try:
        st = os.stat(path)
    except OSError as exc:
        raise IssuerError(f"failed to stat private key file {path!r}: {exc.__class__.__name__}") from None
    if not stat.S_ISREG(st.st_mode):
        raise IssuerError(f"private key file {path!r} is not a regular file")
    if os.name != "nt":
        mode = stat.S_IMODE(st.st_mode)
        if mode & _UNSAFE_PRIVATE_KEY_MODE_MASK:
            raise IssuerError(
                f"refusing to read private key file {path!r}: its POSIX mode {oct(mode)} is "
                "group/other-accessible - `chmod 600` it (owner read/write only) before retrying"
            )

    try:
        with open(path, "rb") as handle:
            raw = handle.read()
    except OSError as exc:
        raise IssuerError(f"failed to read private key file {path!r}: {exc.__class__.__name__}") from None
    if len(raw) != PRIVATE_KEY_RAW_BYTES:
        raise IssuerError(f"private key file {path!r} must contain exactly {PRIVATE_KEY_RAW_BYTES} raw bytes, found {len(raw)}")
    try:
        return Ed25519PrivateKey.from_private_bytes(raw)
    except ValueError:
        raise IssuerError(f"private key file {path!r} does not contain a valid Ed25519 private key") from None
    finally:
        raw = None  # best-effort - CPython bytes are immutable, but drop the reference promptly


@dataclasses.dataclass(frozen=True)
class IssuerIdentity:
    issuer_key_id: str
    public_key_bytes: bytes  # exactly PUBLIC_KEY_RAW_BYTES bytes


def read_issuer_metadata_file(path: str) -> IssuerIdentity:
    """Strictly parses the EXACT public metadata JSON `generate-key`
    produces (PR #95 review fix, item 1) - requires exactly the three
    fields `issuerKeyId`/`publicKeyBase64`/`publicKeyFingerprintSha256Hex`,
    validates each, and cross-checks that the fingerprint actually matches
    SHA-256(publicKeyBase64) - a metadata file that is internally
    inconsistent (e.g. hand-edited) is rejected rather than trusted. This
    function never reads or needs the private key; `cmd_issue` separately
    verifies the private key's OWN derived public key matches
    `public_key_bytes` returned here before any activation is created."""
    try:
        with open(path, "r", encoding="utf-8") as handle:
            raw = handle.read()
    except OSError as exc:
        raise IssuerError(f"failed to read issuer metadata file {path!r}: {exc.__class__.__name__}") from None
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise IssuerError(f"issuer metadata file {path!r} is not valid JSON: {exc}") from None
    if not isinstance(data, dict) or set(data.keys()) != _ISSUER_METADATA_REQUIRED_FIELDS:
        raise IssuerError(
            f"issuer metadata file {path!r} must contain EXACTLY the fields "
            f"{sorted(_ISSUER_METADATA_REQUIRED_FIELDS)} - no more, no fewer"
        )

    issuer_key_id = data["issuerKeyId"]
    if not isinstance(issuer_key_id, str):
        raise IssuerError("issuer metadata issuerKeyId must be a string")
    validate_issuer_key_id(issuer_key_id)

    public_key_b64 = data["publicKeyBase64"]
    if not isinstance(public_key_b64, str):
        raise IssuerError("issuer metadata publicKeyBase64 must be a string")
    try:
        public_key_bytes = base64.b64decode(public_key_b64, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise IssuerError(f"issuer metadata publicKeyBase64 is not valid strict base64: {exc}") from None
    if len(public_key_bytes) != PUBLIC_KEY_RAW_BYTES:
        raise IssuerError(f"issuer metadata publicKeyBase64 must decode to exactly {PUBLIC_KEY_RAW_BYTES} bytes, got {len(public_key_bytes)}")

    fingerprint = data["publicKeyFingerprintSha256Hex"]
    if not isinstance(fingerprint, str) or not _FINGERPRINT_RE.match(fingerprint):
        raise IssuerError("issuer metadata publicKeyFingerprintSha256Hex must be exactly 64 lowercase hex characters")

    computed_fingerprint = hashlib.sha256(public_key_bytes).hexdigest()
    if not hmac.compare_digest(computed_fingerprint, fingerprint):
        raise IssuerError(
            f"issuer metadata file {path!r} is internally inconsistent: SHA-256(publicKeyBase64) does not "
            "match publicKeyFingerprintSha256Hex - refusing to trust a corrupted/hand-edited metadata file"
        )

    return IssuerIdentity(issuer_key_id=issuer_key_id, public_key_bytes=public_key_bytes)


def _resolve_ancestors(path: str):
    current = os.path.abspath(path)
    while True:
        yield current
        parent = os.path.dirname(current)
        if parent == current:
            return
        current = parent


def _refuse_if_inside_git_repo(path: str) -> None:
    """Best-effort, reliable-enough detection: refuses an output path if
    ANY ancestor directory (starting from the path's own parent) contains
    a `.git` entry. This is NOT a security boundary against a determined
    operator, only a guardrail against an accidental `--private-key-out`/
    `--out` inside a git working tree - see module docs."""
    directory = os.path.dirname(os.path.abspath(path)) or "."
    for ancestor in _resolve_ancestors(directory):
        if os.path.exists(os.path.join(ancestor, ".git")):
            raise IssuerError(
                f"refusing to write {path!r}: {ancestor!r} is (or is inside) a git repository - "
                "choose an output path outside any git working tree"
            )


def _refuse_if_exists(path: str) -> None:
    if os.path.exists(path):
        raise IssuerError(f"refusing to overwrite existing file: {path!r}")


def _write_temp_secret_file(directory: str, data: bytes) -> str:
    """Writes `data` to a fresh, 0600-where-supported sibling temp file in
    `directory`, fsyncs it, and returns its path - NEVER the final
    publication step (see `publish_secret_no_clobber`). On any failure the temp
    file is removed before the exception propagates."""
    os.makedirs(directory, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".activation-envelope-issuer.", suffix=".tmp")
    try:
        try:
            os.chmod(tmp_path, 0o600)
        except OSError:
            # Windows: os.chmod's owner-write bit is a poor analogue of
            # POSIX 0600 and provides no group/other ACL guarantee - see
            # module/docs' own truthful platform-limitation note. Best
            # effort only; never treated as a security guarantee here.
            pass
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
    return tmp_path


def _print_durability_warning(message: str) -> None:
    """PR #95 review fix (round 3) - BEST-EFFORT ONLY, by construction: a
    diagnostic warning must NEVER itself become a transaction failure. Any
    exception raised while attempting to print it (closed stderr,
    `BrokenPipeError`, a patched/custom stream raising `RuntimeError`,
    etc.) is swallowed here - silently, since there is nothing safer left
    to do once even the warning channel itself is failing, and this
    function is only ever called AFTER the artifact it describes has
    already been successfully published."""
    try:
        print(f"activation_envelope_issuer: WARNING - durability: {message}", file=sys.stderr)
    except Exception:
        pass


def publish_secret_no_clobber(path: str, data: bytes) -> str:
    """PR #95 review fix (round 3) - PRE-COMMIT and COMMIT ONLY, and
    NOTHING else. Writes `data` to a fresh sibling temp file (0600 where
    supported), fsyncs it, then atomically publishes it to `path` via a
    no-clobber `os.link` - the OS itself guarantees this fails atomically
    with `FileExistsError` if `path` already exists, closing the TOCTOU
    race an earlier `if os.path.exists(...): ... ; os.replace(...)`
    pattern was vulnerable to (a concurrent writer creating the
    destination in the gap between the check and the replace would have
    been silently overwritten). If the underlying filesystem cannot
    provide this no-clobber guarantee at all (`os.link` raises anything
    other than `FileExistsError`), this fails closed - it never falls back
    to an overwrite-capable write.

    Raises `IssuerError` ONLY for a PRE-COMMIT failure (the temp write/
    fsync, or the final link itself failing/being refused) - `path` was
    never created in that case, so propagating freely is correct.

    THE INSTANT `os.link` SUCCEEDS, THIS FUNCTION RETURNS - it performs NO
    further fallible work (no temp-name cleanup, no directory fsync, no
    diagnostics) before doing so. This is deliberate: a caller's
    rollback/revocation `try` block can end its commit-covered region
    IMMEDIATELY after calling this function, with ZERO risk of a
    post-commit housekeeping failure being misinterpreted as a
    publication failure and triggering a rollback of work that has
    already succeeded. `path` is successfully published and its file
    contents were fsynced before this function returns - directory-entry
    crash durability is a SEPARATE, later confirmation; see
    `confirm_post_publication`, which the caller must invoke afterward,
    OUTSIDE any rollback region, using the `tmp_path` this function
    returns.
    """
    directory = os.path.dirname(os.path.abspath(path)) or "."
    tmp_path = _write_temp_secret_file(directory, data)
    try:
        os.link(tmp_path, path)
    except FileExistsError:
        # PRE-commit failure - `path` was never created. `tmp_path` is
        # still ours alone; clean it up before raising.
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise IssuerError(f"refusing to overwrite existing file: {path!r}") from None
    except OSError as exc:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise IssuerError(
            f"atomic no-clobber publication is not supported for {path!r} "
            f"({exc.__class__.__name__}) - refusing to fall back to an overwrite-capable write"
        ) from None

    # --- COMMITTED: `path` now exists and is complete. Return immediately;
    # --- no further fallible work happens in this function. ---
    return tmp_path


@dataclasses.dataclass(frozen=True)
class PostPublicationResult:
    """POST-commit-only outcome of `confirm_post_publication` - see that
    function's own docs. NEITHER field ever implies the published file is
    anything other than successfully published and fsynced; both report
    SEPARATE, purely additional confirmations that may or may not also
    have succeeded."""

    temp_cleanup_confirmed: bool
    directory_sync_confirmed: bool


def confirm_post_publication(path: str, tmp_path: str) -> PostPublicationResult:
    """PR #95 review fix (round 3) - POST-COMMIT ONLY. The caller MUST
    only invoke this AFTER `publish_secret_no_clobber(path, ...)` has
    already returned successfully, and OUTSIDE any rollback/revocation
    region - this function itself NEVER raises, under any circumstance,
    including from its own warning output (`_print_durability_warning` is
    itself best-effort). It does two purely additional, independent
    things, neither of which can ever un-publish `path` or imply it
    should be treated as unpublished:

      1. removes the now-redundant `tmp_path` hardlink (cosmetic only -
         `path` and `tmp_path` refer to the SAME inode, so removing the
         temp name can never affect `path`'s own content);
      2. attempts to fsync `path`'s containing directory - an ADDITIONAL,
         separate crash-durability confirmation for the directory ENTRY
         itself, not `path`'s file contents (already fsynced by
         `publish_secret_no_clobber` before it returned).

    A failure in either step is reported ONLY via the returned dataclass
    plus a best-effort printed warning - NEVER an exception, and never a
    reason to revoke anything or delete `path`. `path` remains
    successfully published and its file contents remain fsynced
    regardless of what this function's return value says; only
    directory-entry crash durability may be reported as unconfirmed - see
    module docs for why this distinction is never blurred into a single
    "durably exists" claim.
    """
    directory = os.path.dirname(os.path.abspath(path)) or "."

    temp_cleanup_confirmed = True
    try:
        os.unlink(tmp_path)
    except OSError as exc:
        temp_cleanup_confirmed = False
        _print_durability_warning(
            f"failed to remove the now-redundant temporary file after successfully publishing {path!r} "
            f"({exc.__class__.__name__}) - {path!r} is successfully published and its file contents were "
            "already fsynced; the leftover temp file is harmless clutter and may be removed manually"
        )

    directory_sync_confirmed = True
    try:
        dir_fd = os.open(directory, os.O_RDONLY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
    except OSError as exc:
        directory_sync_confirmed = False
        _print_durability_warning(
            f"directory fsync failed for {directory!r} after {path!r} was already successfully published "
            f"({exc.__class__.__name__}) - {path!r} is successfully published and its file contents were "
            "fsynced before publication; directory-entry crash durability could not be confirmed - "
            "investigate before distributing/relying on this artifact"
        )

    return PostPublicationResult(temp_cleanup_confirmed=temp_cleanup_confirmed, directory_sync_confirmed=directory_sync_confirmed)


# --- generate-key ---

def public_key_fingerprint_sha256_hex(public_key: Ed25519PublicKey) -> str:
    pub_bytes = public_key.public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)
    return hashlib.sha256(pub_bytes).hexdigest()


def public_key_base64(public_key: Ed25519PublicKey) -> str:
    pub_bytes = public_key.public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)
    return base64.b64encode(pub_bytes).decode("ascii")


def cmd_generate_key(args) -> int:
    validate_issuer_key_id(args.key_id)
    _refuse_if_exists(args.private_key_out)
    _refuse_if_exists(args.public_metadata_out)
    _refuse_if_inside_git_repo(args.private_key_out)
    _refuse_if_inside_git_repo(args.public_metadata_out)

    private_key = Ed25519PrivateKey.generate()
    public_key = private_key.public_key()
    fingerprint = public_key_fingerprint_sha256_hex(public_key)
    metadata = {
        "issuerKeyId": args.key_id,
        "publicKeyBase64": public_key_base64(public_key),
        "publicKeyFingerprintSha256Hex": fingerprint,
    }
    metadata_bytes = (json.dumps(metadata, indent=2) + "\n").encode("utf-8")

    # PR #95 review fix (round 3) - PUBLIC metadata is published FIRST via
    # publish_secret_no_clobber, which returns as soon as its commit (the
    # final link) succeeds and does NO further fallible work. If this
    # fails, NO private key file has ever been written - the "command
    # failure before private-key commit -> no private key file remains"
    # invariant holds trivially by ordering alone.
    metadata_tmp_path = publish_secret_no_clobber(args.public_metadata_out, metadata_bytes)

    # PRIVATE key is published SECOND. The SENSITIVE COMMIT POINT is
    # precisely the successful no-clobber final-path link inside
    # publish_secret_no_clobber - not this function returning, not any
    # later housekeeping. If the private key's link NEVER succeeds (a
    # PRE-commit failure), no private key file exists at all, and we
    # deliberately do NOT delete the metadata we already published: an
    # unconditional `os.remove(args.public_metadata_out)` would delete
    # WHATEVER currently occupies that pathname - which could, in a real
    # race, be a completely different file a concurrent actor placed there
    # after our own publish - a genuine TOCTOU cleanup race. The metadata
    # is PUBLIC data that cannot sign anything by itself; `issue` already
    # requires its public key to match a private key's OWN derived public
    # key, so an orphaned metadata file with no matching private key is
    # simply unusable, never a security risk - a harmless public orphan is
    # strictly preferable to a pathname-based deletion race. See
    # docs/B56_ACTIVATION_ISSUER_KEY_CEREMONY.md's "metadata orphan policy".
    priv_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    try:
        key_tmp_path = publish_secret_no_clobber(args.private_key_out, priv_bytes)
    except BaseException:
        print(
            f"activation_envelope_issuer: ERROR - private key publication failed before its final path was "
            f"created; no private key file exists. Public metadata at {args.public_metadata_out!r} was already "
            "published and is deliberately LEFT IN PLACE - it is public data that cannot sign anything without "
            "a matching private key, and this command never deletes an existing pathname it does not currently "
            "control the identity of (see docs/B56_ACTIVATION_ISSUER_KEY_CEREMONY.md's 'metadata orphan policy').",
            file=sys.stderr,
        )
        raise
    finally:
        priv_bytes = None

    # --- PRIVATE KEY COMMIT HAS HAPPENED. Nothing below this line may ever
    # --- delete either file, no matter what a post-commit confirmation
    # --- step or a later print statement does. Both
    # --- confirm_post_publication calls below NEVER raise (see their own
    # --- docs) - they exist purely to report additional, non-essential
    # --- durability/cleanup confirmations, never to gate success.
    metadata_publication = confirm_post_publication(args.public_metadata_out, metadata_tmp_path)
    key_publication = confirm_post_publication(args.private_key_out, key_tmp_path)

    print(f"activation_envelope_issuer: generated activation-issuer key id={args.key_id}")
    print(f"activation_envelope_issuer: public key fingerprint (sha256)={fingerprint}")
    print(f"activation_envelope_issuer: private key written to {args.private_key_out} (raw {PRIVATE_KEY_RAW_BYTES} bytes - "
          "KEEP OFFLINE, never commit, never transmit)")
    print(f"activation_envelope_issuer: public metadata written to {args.public_metadata_out}")
    if not metadata_publication.directory_sync_confirmed or not key_publication.directory_sync_confirmed:
        print(
            "activation_envelope_issuer: NOTE - see the durability warning(s) above: both files are "
            "successfully published and their contents are fsynced, but directory-entry crash durability "
            "could not be confirmed for at least one of them.",
            file=sys.stderr,
        )
    if os.name == "nt":
        print(
            "activation_envelope_issuer: WARNING - this is a Windows filesystem; POSIX 0600 permissions "
            "were NOT applied (os.chmod's owner-write bit is not an ACL guarantee on Windows). Restrict "
            "access to this file's directory manually (e.g. NTFS ACLs) before leaving it on this machine.",
            file=sys.stderr,
        )
    return 0


# --- optional --bootstrap-bundle inspection (strict, read-only, non-trust) ---

def inspect_signed_manifest_bundle(path: str) -> Tuple[int, bytes]:
    """Strict, READ-ONLY inspection of an EXISTING SignedManifestCodec
    artifact (produced by gateway/tools/manifest_signing.py's
    sign-and-package command) - returns (manifest_version, sha256_of_exact_file_bytes).
    This is operator-side metadata inspection ONLY - it never re-signs,
    never becomes a trust decision, and never modifies manifest signing
    semantics. Validates the SAME outer-container shape SignedManifestCodec.decode
    (Kotlin) enforces - format version, canonical/signature length bounds,
    exact-container (no trailing bytes) - then reads only as much of the
    (already-validated-length) canonical prefix as needed to extract the
    manifest version, without parsing endpoints at all.

    Raises BundleInspectionError on ANY malformed/truncated/oversized
    input - never returns a partial result.

    PR #95 review fix (round 2, item 3): the file's SIZE ON DISK is checked
    against `_SIGNED_MANIFEST_MAX_TOTAL_BYTES` via `os.path.getsize` BEFORE
    the file is read into memory at all - an obviously over-bound file is
    rejected without ever allocating a buffer for its contents. The bound
    is derived directly from the SAME existing codec constants used below
    (outer header + `_SIGNED_MANIFEST_MAX_CANONICAL_BYTES` +
    `_SIGNED_MANIFEST_SIGNATURE_LENGTH`), never a second independently-
    chosen limit."""
    try:
        file_size = os.path.getsize(path)
    except OSError as exc:
        raise BundleInspectionError(f"failed to stat bootstrap bundle {path!r}: {exc.__class__.__name__}") from None
    if file_size > _SIGNED_MANIFEST_MAX_TOTAL_BYTES:
        raise BundleInspectionError(
            f"bootstrap bundle {path!r} is {file_size} bytes, exceeding the maximum plausible "
            f"SignedManifestCodec container size ({_SIGNED_MANIFEST_MAX_TOTAL_BYTES} bytes) - "
            "refusing to read it into memory"
        )

    try:
        with open(path, "rb") as handle:
            raw = handle.read()
    except OSError as exc:
        raise BundleInspectionError(f"failed to read bootstrap bundle {path!r}: {exc.__class__.__name__}") from None

    offset = 0

    def _read_i32() -> int:
        nonlocal offset
        if offset + 4 > len(raw):
            raise BundleInspectionError("bootstrap bundle is truncated (expected a 4-byte length/version field)")
        value = struct.unpack_from(">i", raw, offset)[0]
        offset += 4
        return value

    outer_format_version = _read_i32()
    if outer_format_version != 1:
        raise BundleInspectionError(f"unsupported signed-manifest container format: {outer_format_version}")

    canonical_len = _read_i32()
    if canonical_len < 0 or canonical_len > _SIGNED_MANIFEST_MAX_CANONICAL_BYTES:
        raise BundleInspectionError(f"implausible canonical manifest length: {canonical_len}")
    if offset + canonical_len > len(raw):
        raise BundleInspectionError("bootstrap bundle is truncated (canonical section shorter than declared)")
    canonical_start = offset
    offset += canonical_len

    signature_len = _read_i32()
    # PR #95 review fix (round 2, item 2) - SignedManifestCodec's own
    # container only bounds signature length generically (0..256), but the
    # REAL client trust boundary (Ed25519ManifestVerifier) requires exactly
    # a 64-byte Ed25519 signature. This is still metadata inspection only -
    # no cryptographic verification happens here - but a bundle whose
    # declared signature length could never be a valid Ed25519 signature is
    # rejected up front rather than silently accepted as "plausible".
    if signature_len != _SIGNED_MANIFEST_SIGNATURE_LENGTH:
        raise BundleInspectionError(
            f"signature length must be exactly {_SIGNED_MANIFEST_SIGNATURE_LENGTH} bytes (Ed25519), got {signature_len}"
        )
    if offset + signature_len > len(raw):
        raise BundleInspectionError("bootstrap bundle is truncated (signature section shorter than declared)")
    offset += signature_len

    if offset != len(raw):
        raise BundleInspectionError(f"trailing bytes after signed-manifest container (expected EOF): {len(raw) - offset} extra byte(s)")

    # Only the canonical manifest's OWN format version + manifestVersion int
    # are read here - never endpoints. Mirrors ManifestCanonicalizer's field
    # order (FORMAT_VERSION, manifestVersion, ...) without duplicating its
    # full endpoint-parsing logic.
    if canonical_len < 8:
        raise BundleInspectionError("canonical manifest section too short to contain a format version and manifestVersion")
    manifest_canonical_format_version = struct.unpack_from(">i", raw, canonical_start)[0]
    if manifest_canonical_format_version != 1:
        raise BundleInspectionError(f"unsupported manifest canonical format version: {manifest_canonical_format_version}")
    manifest_version = struct.unpack_from(">i", raw, canonical_start + 4)[0]
    if manifest_version < 1:
        raise BundleInspectionError(f"implausible manifestVersion: {manifest_version}")

    # Hash the EXACT file bytes - never just the canonical section, never a
    # reserialized representation - see module docs.
    content_hash = hashlib.sha256(raw).digest()
    return manifest_version, content_hash


# --- endpoint hints (operator CLI argument parsing) ---

def _validate_hints_order_preserving(hints: Sequence[str]) -> Tuple[str, ...]:
    if len(hints) > MAX_ENDPOINT_HINTS:
        raise IssuerError(f"too many --endpoint-hint arguments ({len(hints)} > {MAX_ENDPOINT_HINTS})")
    if len(set(hints)) != len(hints):
        raise IssuerError("--endpoint-hint values must not contain a duplicate")
    for hint in hints:
        # Matches Android EndpointId's isNotBlank() exactly (PR #95 review
        # fix, item 3) - a whitespace-only hint like " " must be rejected
        # here, BEFORE issuance, not discovered later as an Android decode
        # failure on an already-signed, already-issued envelope.
        if not hint.strip():
            raise IssuerError("--endpoint-hint must not be blank or whitespace-only")
        hint_bytes = _utf8_bytes_or_raise(hint, "--endpoint-hint")
        if len(hint_bytes) > MAX_ENDPOINT_HINT_UTF8_BYTES:
            raise IssuerError(f"--endpoint-hint {hint!r} exceeds max UTF-8 byte length ({MAX_ENDPOINT_HINT_UTF8_BYTES}): {len(hint_bytes)}")
    return tuple(hints)  # ORIGINAL ORDER - never sorted/deduplicated-and-reordered


def _require_finite_positive(value: float, name: str, max_value: float) -> None:
    """PR #95 review fix (item 9) - `argparse type=float` happily accepts
    `nan`/`inf`/`-inf` text; a plain `value <= 0 or value > max_value`
    check does NOT reject NaN (every comparison with NaN is False). This
    is the ONE place both time arguments are validated, BEFORE
    issue_activation() is ever called."""
    if not math.isfinite(value) or value <= 0 or value > max_value:
        raise IssuerError(f"{name} must be a finite, positive number no greater than {max_value} (got {value!r})")


# --- issue ---

def cmd_issue(args) -> int:
    # Steps 1-4: validate EVERY local/operator input BEFORE touching the
    # activation store - see module's atomicity requirement.
    _require_finite_positive(args.envelope_valid_for_hours, "--envelope-valid-for-hours", _MAX_ENVELOPE_VALID_FOR_HOURS)
    if args.activation_expires_in_days is not None:
        _require_finite_positive(args.activation_expires_in_days, "--activation-expires-in-days", _MAX_ACTIVATION_EXPIRES_IN_DAYS)

    private_key = read_private_key_file(args.private_key_file)
    public_key = private_key.public_key()
    derived_public_key_bytes = public_key.public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)

    # PR #95 review fix (item 1) - the issuer key id comes ONLY from the
    # metadata generated alongside the private key, never an independently
    # operator-typed value, and the private key's OWN derived public key
    # must match that metadata's public key byte-for-byte. Any mismatch
    # fails BEFORE issue_activation() - no activation is ever created.
    identity = read_issuer_metadata_file(args.issuer_metadata_file)
    if not hmac.compare_digest(identity.public_key_bytes, derived_public_key_bytes):
        raise IssuerError(
            "--private-key-file does not match the public key recorded in --issuer-metadata-file - "
            "refusing to sign an envelope with issuerKeyId that no client could ever verify against this key"
        )
    issuer_key_id = identity.issuer_key_id

    _refuse_if_exists(args.out)
    _refuse_if_inside_git_repo(args.out)

    hints = _validate_hints_order_preserving(args.endpoint_hint or [])

    bundle_ref: Optional[BundleRef] = None
    if args.bootstrap_bundle:
        try:
            manifest_version, content_hash = inspect_signed_manifest_bundle(args.bootstrap_bundle)
        except BundleInspectionError as exc:
            raise IssuerError(f"--bootstrap-bundle rejected: {exc}") from None
        bundle_ref = BundleRef(manifest_version=manifest_version, content_hash=content_hash)

    # Step 5: only now call the EXISTING, unmodified issuance authority.
    activations_module = _activations_module()
    try:
        activation_id, credential = activations_module.issue_activation(
            args.store, args.lock, args.max_devices, args.activation_expires_in_days,
        )
    except (activations_module.ActivationStoreError, ValueError) as exc:
        raise IssuerError(f"issue_activation failed: {exc}") from None

    # Everything from here on MUST either succeed all the way through the
    # successful no-clobber publication of the artifact (the TRANSACTION
    # COMMIT POINT - PR #95 review fix) or revoke the activation just
    # created - never leave a plaintext-credential activation ACTIVE with
    # no delivered envelope, and never revoke an activation whose envelope
    # was already successfully published (its file contents fsynced
    # before that commit) merely because a later, purely additional
    # confirmation step failed. See module's CRITICAL ATOMICITY requirement.
    try:
        # PR #95 review fix (item 10) - a newly-issued activation that
        # cannot be read back at all is an invariant violation, not a
        # silently-ignored edge case; this must trigger the same rollback
        # path as any other post-issue failure.
        record = activations_module.find_by_activation_id(args.store, args.lock, activation_id)
        if record is None:
            raise IssuerError(f"invariant violation: newly-issued activation_id={activation_id} could not be read back from the store")

        issued_at = int(time.time() * 1000)
        not_before = issued_at
        requested_expires_at = issued_at + int(args.envelope_valid_for_hours * 3600 * 1000)

        server_expires_at = None
        if record.get("expires_at"):
            from datetime import datetime

            server_expires_at = int(datetime.fromisoformat(record["expires_at"]).timestamp() * 1000)

        if server_expires_at is not None and requested_expires_at > server_expires_at:
            # FAIL LOUDLY rather than silently clamping - chosen over
            # silent clamping because every other explicit CLI input in
            # this tool (--envelope-valid-for-hours itself) is required,
            # never silently substituted; an operator who asked for a
            # longer envelope than the entitlement allows almost
            # certainly made a mistake worth surfacing, not quietly
            # correcting. See module docs / B56_ACTIVATION_ISSUER_KEY_CEREMONY.md.
            raise IssuerError(
                f"requested envelope lifetime (expiring at epoch millis {requested_expires_at}) would extend "
                f"beyond this activation's own server-side expiry (epoch millis {server_expires_at}) - "
                "reduce --envelope-valid-for-hours or issue a longer-lived activation"
            )
        expires_at = requested_expires_at

        envelope = ActivationEnvelope(
            activation_id=activation_id,
            credential=credential,
            issued_at_epoch_millis=issued_at,
            not_before_epoch_millis=not_before,
            expires_at_epoch_millis=expires_at,
            bootstrap_bundle_ref=bundle_ref,
            bootstrap_endpoint_hints=hints,
            bootstrap_capability_hint=None,
            nonce=secrets.token_bytes(NONCE_LENGTH),
            issuer_key_id=issuer_key_id,
        )

        canonical = canonical_bytes(envelope)
        signature = private_key.sign(canonical)
        artifact = pack_signed_envelope(canonical, signature)
        # PR #95 review fix (round 3) - the hash is computed BEFORE
        # publication, and publish_secret_no_clobber is the LAST
        # operation inside this rollback region: it returns as soon as
        # its commit (the final no-clobber link) succeeds and performs NO
        # further fallible work - see its own docs. This is what makes it
        # safe for this `try` block to end immediately afterward: there is
        # no post-commit housekeeping left inside the rollback region at
        # all for a stray failure to be misattributed to.
        artifact_sha256 = hashlib.sha256(artifact).hexdigest()
        artifact_tmp_path = publish_secret_no_clobber(args.out, artifact)
    except BaseException as exc:
        _revoke_or_report_critical(args, activation_id, exc)
        return 1
    finally:
        credential = None  # best-effort - drop the local reference promptly

    # --- COMMIT HAS HAPPENED: the envelope artifact is successfully
    # --- published and its file contents were fsynced, and the activation
    # --- remains ACTIVE. `revoke_activation()` can no longer be reached
    # --- from any code path below this line - confirm_post_publication
    # --- NEVER raises (see its own docs), so nothing here can trigger a
    # --- rollback of a transaction that has already committed.
    publication = confirm_post_publication(args.out, artifact_tmp_path)

    print(f"activation_envelope_issuer: activation_id={activation_id} issuerKeyId={issuer_key_id}")
    print(f"activation_envelope_issuer: envelope issuedAt={issued_at} expiresAt={expires_at} max_devices={args.max_devices}")
    print(f"activation_envelope_issuer: issuer public key fingerprint (sha256)={public_key_fingerprint_sha256_hex(public_key)}")
    print(f"activation_envelope_issuer: envelope artifact written to {args.out} (sha256={artifact_sha256})")
    if not publication.directory_sync_confirmed:
        print(
            "activation_envelope_issuer: NOTE - see the durability warning above: the envelope artifact is "
            "successfully published and its file contents are fsynced, but directory-entry crash durability "
            "could not be confirmed.",
            file=sys.stderr,
        )
    if bundle_ref is not None:
        print(f"activation_envelope_issuer: bootstrap bundle manifestVersion={bundle_ref.manifest_version} contentHash(sha256)={bundle_ref.content_hash.hex()}")
    return 0


def _revoke_or_report_critical(args, activation_id: str, original_exc: BaseException) -> None:
    """CRITICAL ATOMICITY - see module docs. PR #95 review fix (item 5):
    NEVER prints `str(original_exc)` (or any revocation-failure exception's
    message) - by this point `issue_activation()` has already produced the
    plaintext credential, and a future lower-layer exception's message
    could conceivably embed sensitive input. Only bounded, structurally
    non-secret diagnostics are printed: a fixed phase description, the
    exception's CLASS NAME, and the (non-secret) activation_id. Always
    non-zero exit; the caller (`cmd_issue`) already returns 1."""
    print(
        f"activation_envelope_issuer: ERROR - envelope creation/signing/output failed after activation "
        f"{activation_id} was created (failure type: {original_exc.__class__.__name__})",
        file=sys.stderr,
    )
    try:
        _activations_module().revoke_activation(args.store, args.lock, activation_id)
    except Exception as revoke_exc:  # noqa: BLE001 - must never propagate a raw traceback here
        print(
            f"activation_envelope_issuer: CRITICAL - failed to auto-revoke activation_id={activation_id} "
            f"(revocation failure type: {revoke_exc.__class__.__name__}). MANUAL REVOCATION REQUIRED: run "
            f"'activation_tokens.py --store {args.store} --lock {args.lock} revoke {activation_id}' now.",
            file=sys.stderr,
        )
        return
    print(
        f"activation_envelope_issuer: activation_id={activation_id} was automatically REVOKED "
        "because its envelope artifact was never successfully delivered.",
        file=sys.stderr,
    )


# --- CLI wiring ---

def cmd_verify_key(args) -> int:
    """B56-4B2 - proves a private key file (the primary copy OR an offline
    backup copy) is the exact key named by the public metadata, WITHOUT
    signing anything, touching any activation store, or emitting any
    private material. Output is public data only: issuerKeyId and the
    public-key SHA-256 fingerprint. With --expected-fingerprint the
    operator additionally pins the out-of-band recorded fingerprint (e.g.
    the one in docs/B56_ACTIVATION_ISSUER_KEY_CEREMONY.md)."""
    private_key = read_private_key_file(args.private_key_file)
    derived = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw,
    )
    private_key = None
    identity = read_issuer_metadata_file(args.issuer_metadata_file)
    if not hmac.compare_digest(identity.public_key_bytes, derived):
        raise IssuerError("--private-key-file does NOT match the public key recorded in --issuer-metadata-file")
    fingerprint = hashlib.sha256(derived).hexdigest()
    if args.expected_fingerprint is not None:
        expected = args.expected_fingerprint.strip().lower()
        if not _FINGERPRINT_RE.match(expected):
            raise IssuerError("--expected-fingerprint must be exactly 64 hex characters")
        if not hmac.compare_digest(expected, fingerprint):
            raise IssuerError("key fingerprint does NOT match --expected-fingerprint")
    print(f"OK issuerKeyId={identity.issuer_key_id} publicKeyFingerprintSha256Hex={fingerprint}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="activation_envelope_issuer.py",
        description="B56-4A operator-only ActivationEnvelope issuer CLI (separate from activation_tokens.py)",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate-key", help="generate a new activation-issuer Ed25519 keypair (private key file-based only)")
    gen.add_argument("--key-id", required=True, help="the issuerKeyId this key will sign envelopes under")
    gen.add_argument("--private-key-out", required=True, help="output path for the raw 32-byte private key (refuses to overwrite)")
    gen.add_argument("--public-metadata-out", required=True, help="output path for public metadata JSON (issuerKeyId/publicKeyBase64/fingerprint - no private material)")

    issue = sub.add_parser("issue", help="issue a new activation and a signed ActivationEnvelope for it")
    issue.add_argument("--store", required=True, help="path to activations.json (same store activation_tokens.py uses)")
    issue.add_argument("--lock", help="path to the activation store lock file (default: <store>.lock)")
    issue.add_argument("--issuer-metadata-file", required=True, help="the EXACT public-metadata JSON generate-key produced alongside --private-key-file - its issuerKeyId is used, and its public key MUST match the private key")
    issue.add_argument("--private-key-file", required=True, help="path to a raw 32-byte Ed25519 private key file - NEVER pass the key itself on the command line")
    issue.add_argument("--max-devices", type=int, default=1, help="device limit for the new activation (default: 1)")
    issue.add_argument("--activation-expires-in-days", type=float, default=None, help="optional server-side activation entitlement expiry, in days from now")
    issue.add_argument("--envelope-valid-for-hours", type=float, required=True, help="REQUIRED - how long the signed envelope itself remains valid, in hours (architecture guidance: roughly 24-72h, not mandated)")
    issue.add_argument("--endpoint-hint", action="append", default=[], help="optional, repeatable, non-authoritative EndpointId hint (order preserved, max 32, no duplicates)")
    issue.add_argument("--bootstrap-bundle", default=None, help="optional path to an ALREADY-signed SignedManifestCodec artifact (from manifest_signing.py) to correlate by exact-byte SHA-256 + manifest version - never re-signed")
    issue.add_argument("--out", required=True, help="output path for the signed envelope artifact - SECRET (contains the plaintext activation credential); refuses to overwrite")

    verify = sub.add_parser("verify-key", help="prove a private key file (primary or backup copy) matches the issuer metadata - prints public data only")
    verify.add_argument("--private-key-file", required=True, help="path to a raw 32-byte Ed25519 private key file (primary or backup copy)")
    verify.add_argument("--issuer-metadata-file", required=True, help="the public metadata JSON generate-key produced")
    verify.add_argument("--expected-fingerprint", default=None, help="optional out-of-band recorded public-key SHA-256 fingerprint (64 hex) to pin")

    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "issue" and not args.lock:
        args.lock = args.store + ".lock"
    try:
        if args.command == "generate-key":
            return cmd_generate_key(args)
        if args.command == "issue":
            return cmd_issue(args)
        if args.command == "verify-key":
            return cmd_verify_key(args)
    except IssuerError as exc:
        print(f"activation_envelope_issuer: error: {exc}", file=sys.stderr)
        return 1
    return 1


if __name__ == "__main__":
    sys.exit(main())
