#!/usr/bin/env python3
"""B56-4A - operator-only ActivationEnvelope issuer CLI.

This is a SEPARATE tool from gateway/tools/activation_tokens.py (the
existing activation-lifecycle CLI, unchanged and unaffected by this file)
and from gateway/tools/manifest_signing.py (the EXISTING, separate manifest
signing authority). It holds a NEW, delegated activation-issuer Ed25519
private key - never the manifest signing key - and produces a signed
`ActivationEnvelope` (net.pocvpn.client.activation.ActivationEnvelope on the
Android side) that is byte-for-byte compatible with
ActivationEnvelopeCanonicalizer.canonicalBytes()/ActivationEnvelopeCodec.

## Two separate authorities, never crossed

    activation-issuer key  -> ActivationEnvelope   (THIS file)
    manifest signing key   -> EndpointManifest / SignedBootstrapBundle (manifest_signing.py, UNCHANGED)

This tool never signs a manifest, never creates an endpoint fact, never
authorizes a host/IP/port, never uses the manifest private key, and never
adds an activation key to ManifestTrustAnchors. An optional
`--bootstrap-bundle` argument only lets the operator correlate an envelope
with an ALREADY-signed SignedManifest artifact (by exact-byte SHA-256 and
its manifest version) - this tool never re-signs, re-encodes, or modifies
that artifact in any way.

## Existing activation store remains the ONE issuance authority

`issue` calls the EXISTING gateway.api.activations.issue_activation()
directly (imported, never invoked as a subprocess) - activation ID
generation, credential generation/hashing, max_devices, expiry, durable
store locking, and store schema are ALL owned by that module, unchanged.
This file adds a signed envelope wrapper around an activation
issue_activation() already created - it does not reimplement or duplicate
any part of that store.

## Private key handling (B12's `--private-key-b64` weakness NOT repeated)

manifest_signing.py's historical `--private-key-b64`/JSON-stdout
`generate-key` pattern is deliberately NOT reused here - see this module's
own `generate-key`/`issue` commands, which accept ONLY `--private-key-file
PATH` (raw 32 Ed25519 private key bytes) and never print, log, or otherwise
surface private key material.

## B56-4A does NOT perform the production ceremony

No production private key is generated by this task, and no production
activation-issuer public key is populated into Android's
FixedActivationIssuerTrustAnchors - see docs/B56_ACTIVATION_ISSUER_KEY_CEREMONY.md.
That is B56-4B, after this tooling is reviewed.

Requires the `cryptography` package (same existing dev-only dependency as
manifest_signing.py - not a gateway API runtime dependency, never imported
by gateway/api/*). Install with: pip install cryptography
"""
from __future__ import annotations

import argparse
import base64
import dataclasses
import hashlib
import json
import os
import secrets
import struct
import sys
import tempfile
import time
from typing import List, Optional, Sequence, Tuple

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_GATEWAY_DIR = os.path.abspath(os.path.join(_THIS_DIR, ".."))
if _GATEWAY_DIR not in sys.path:
    sys.path.insert(0, _GATEWAY_DIR)

from cryptography.hazmat.primitives.asymmetric.ed25519 import (  # noqa: E402
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives import serialization  # noqa: E402

# --- domain/format constants - MUST exactly match the merged Android B56-1 encoding ---

DOMAIN_TAG = "NOVA_ACTIVATION_ENVELOPE_V1"
CANONICAL_FORMAT_VERSION = 1  # ActivationEnvelopeCanonicalizer.FORMAT_VERSION
CODEC_FORMAT_VERSION = 1  # ActivationEnvelopeCodec's outer container FORMAT_VERSION
SIGNATURE_LENGTH = 64
NONCE_LENGTH = 16  # ActivationEnvelope.NONCE_LENGTH
MAX_ENDPOINT_HINTS = 32  # ActivationEnvelope.MAX_ENDPOINT_HINTS
MAX_ENDPOINT_HINT_UTF8_BYTES = 128  # ActivationEnvelope.MAX_ENDPOINT_HINT_UTF8_BYTES
MAX_ISSUER_KEY_ID_UTF8_BYTES = 64  # ActivationIssuerKeyId.MAX_LENGTH_BYTES
MAX_CREDENTIAL_CHARS = 256  # ActivationCredential.MAX_LENGTH
CONTENT_HASH_LENGTH = 32  # ActivationBundleRef.CONTENT_HASH_LENGTH (SHA-256)
PRIVATE_KEY_RAW_BYTES = 32

_ACTIVATION_ID_RE_SRC = r"^[0-9a-f]{32}$"
_CREDENTIAL_RE_SRC = r"^[A-Za-z0-9_-]+$"

# SignedManifestCodec's own bounds (gateway/tools/manifest_signing.py /
# android SignedManifestCodec.kt) - reused verbatim by
# inspect_signed_manifest_bundle, never a second independently-chosen limit.
_SIGNED_MANIFEST_MAX_CANONICAL_BYTES = 1_000_000
_SIGNED_MANIFEST_MAX_SIGNATURE_BYTES = 256


def _activations_module():
    """Lazy import of gateway.api.activations - deferred (rather than a
    top-level import) ONLY so this module's pure encoding/signing/key-
    generation/bundle-inspection logic remains importable and unit-
    testable on a platform without `fcntl` (e.g. Windows dev machines);
    the real gateway.api.activations module itself is unchanged and still
    Linux-only (flock-based locking), matching production reality. This
    is still a direct Python import and call of the EXISTING module -
    never a subprocess invocation of activation_tokens.py."""
    from api import activations as activations_module

    return activations_module


class IssuerError(Exception):
    """A local/operator-input validation or key/file-handling failure - the
    CLI maps this to a loud, non-zero-exit error. Never constructed with,
    or printed alongside, private key or credential material."""


class BundleInspectionError(Exception):
    """The optional --bootstrap-bundle file failed the strict read-only
    outer-container check below - never a trust decision, purely "this
    artifact is not a well-formed SignedManifestCodec container"."""


# --- ActivationEnvelope canonical encoding - byte-for-byte mirror of ---
# --- ActivationEnvelopeCanonicalizer.kt / ActivationEnvelopeCodec.kt   ---

@dataclasses.dataclass(frozen=True)
class BundleRef:
    manifest_version: int
    content_hash: bytes  # exactly CONTENT_HASH_LENGTH bytes

    def __post_init__(self):
        if self.manifest_version < 1:
            raise IssuerError(f"bundleRef.manifestVersion must be >= 1: {self.manifest_version}")
        if len(self.content_hash) != CONTENT_HASH_LENGTH:
            raise IssuerError(f"bundleRef.contentHash must be exactly {CONTENT_HASH_LENGTH} bytes: {len(self.content_hash)}")


@dataclasses.dataclass(frozen=True)
class ActivationEnvelope:
    activation_id: str
    credential: str
    issued_at_epoch_millis: int
    not_before_epoch_millis: int
    expires_at_epoch_millis: int
    bootstrap_bundle_ref: Optional[BundleRef]
    bootstrap_endpoint_hints: Tuple[str, ...]  # ORDER-PRESERVING - never sorted
    bootstrap_capability_hint: None  # ALWAYS None in B56-4A - see module docs (B56-6 owns this)
    nonce: bytes  # exactly NONCE_LENGTH bytes
    issuer_key_id: str

    def __post_init__(self):
        import re

        if not re.match(_ACTIVATION_ID_RE_SRC, self.activation_id):
            raise IssuerError("activationId must be 32 lowercase hex characters")
        if not self.credential:
            raise IssuerError("credential must not be empty")
        if len(self.credential) > MAX_CREDENTIAL_CHARS:
            raise IssuerError(f"credential exceeds max length ({MAX_CREDENTIAL_CHARS})")
        if not re.match(_CREDENTIAL_RE_SRC, self.credential):
            raise IssuerError("credential must be URL-safe base64 (no padding)")
        if self.not_before_epoch_millis >= self.expires_at_epoch_millis:
            raise IssuerError("notBeforeEpochMillis must be before expiresAtEpochMillis")
        if len(self.nonce) != NONCE_LENGTH:
            raise IssuerError(f"nonce must be exactly {NONCE_LENGTH} bytes: {len(self.nonce)}")
        if len(self.bootstrap_endpoint_hints) > MAX_ENDPOINT_HINTS:
            raise IssuerError(f"too many bootstrapEndpointHints ({len(self.bootstrap_endpoint_hints)} > {MAX_ENDPOINT_HINTS})")
        if len(set(self.bootstrap_endpoint_hints)) != len(self.bootstrap_endpoint_hints):
            raise IssuerError("bootstrapEndpointHints contains a duplicate EndpointId")
        for hint in self.bootstrap_endpoint_hints:
            if not hint:
                raise IssuerError("bootstrapEndpointHint must not be blank")
            hint_bytes = hint.encode("utf-8")
            if len(hint_bytes) > MAX_ENDPOINT_HINT_UTF8_BYTES:
                raise IssuerError(f"bootstrapEndpointHint '{hint}' exceeds max UTF-8 byte length ({MAX_ENDPOINT_HINT_UTF8_BYTES}): {len(hint_bytes)}")
        if self.bootstrap_capability_hint is not None:
            # B56-4A structural rule - see module docs. Not reachable via
            # the CLI (there is no --capability-hint flag), enforced here
            # too so a future programmatic caller cannot silently violate it.
            raise IssuerError("bootstrapCapabilityHint must be None in B56-4A - B56-6 owns this field")
        if not self.issuer_key_id:
            raise IssuerError("issuerKeyId must not be blank")
        issuer_key_id_bytes = self.issuer_key_id.encode("utf-8")
        if len(issuer_key_id_bytes) > MAX_ISSUER_KEY_ID_UTF8_BYTES:
            raise IssuerError(f"issuerKeyId exceeds max UTF-8 byte length ({MAX_ISSUER_KEY_ID_UTF8_BYTES})")


def _write_string(buf: bytearray, s: str) -> None:
    b = s.encode("utf-8")
    buf += struct.pack(">i", len(b))
    buf += b


def _write_bytes(buf: bytearray, b: bytes) -> None:
    buf += struct.pack(">i", len(b))
    buf += b


def canonical_bytes(envelope: ActivationEnvelope) -> bytes:
    """MUST stay byte-identical to ActivationEnvelopeCanonicalizer.canonicalBytes
    (Kotlin) - see that file's own field-order comment. If you change one
    side, change the other and re-run the cross-language compatibility
    test (gateway/tools/tests/test_activation_envelope_issuer.py plus
    ActivationEnvelopePythonCompatibilityTest.kt)."""
    buf = bytearray()
    _write_string(buf, DOMAIN_TAG)
    buf += struct.pack(">i", CANONICAL_FORMAT_VERSION)
    _write_string(buf, envelope.activation_id)
    _write_string(buf, envelope.credential)
    buf += struct.pack(">q", envelope.issued_at_epoch_millis)
    buf += struct.pack(">q", envelope.not_before_epoch_millis)
    buf += struct.pack(">q", envelope.expires_at_epoch_millis)

    ref = envelope.bootstrap_bundle_ref
    buf += struct.pack(">?", ref is not None)
    if ref is not None:
        buf += struct.pack(">i", ref.manifest_version)
        _write_bytes(buf, ref.content_hash)

    hints = envelope.bootstrap_endpoint_hints  # ORDER PRESERVED - never sorted
    buf += struct.pack(">i", len(hints))
    for hint in hints:
        _write_string(buf, hint)

    capability = envelope.bootstrap_capability_hint
    buf += struct.pack(">?", capability is not None)
    if capability is not None:
        _write_bytes(buf, capability)

    _write_bytes(buf, envelope.nonce)
    _write_string(buf, envelope.issuer_key_id)
    return bytes(buf)


def sign_envelope(envelope: ActivationEnvelope, private_key: Ed25519PrivateKey) -> bytes:
    """Signs ONLY the canonical ActivationEnvelope bytes - never a
    manifest, never a JSON/serialized-object representation."""
    return private_key.sign(canonical_bytes(envelope))


def pack_signed_envelope(canonical: bytes, signature: bytes) -> bytes:
    """The EXACT existing ActivationEnvelopeCodec container shape:
    [formatVersion:i32BE=1][canonicalLength:i32BE][canonicalBytes]
    [signatureLength:i32BE=64][signature]. No alternate format, no JSON
    wrapper, no second envelope wire format."""
    if len(signature) != SIGNATURE_LENGTH:
        raise IssuerError(f"signature must be exactly {SIGNATURE_LENGTH} bytes: {len(signature)}")
    buf = bytearray()
    buf += struct.pack(">i", CODEC_FORMAT_VERSION)
    buf += struct.pack(">i", len(canonical))
    buf += canonical
    buf += struct.pack(">i", len(signature))
    buf += signature
    return bytes(buf)


# --- private key file handling - NO CLI secret, ever ---

def read_private_key_file(path: str) -> Ed25519PrivateKey:
    """Reads EXACTLY PRIVATE_KEY_RAW_BYTES (32) raw Ed25519 private key
    bytes from `path`. Never accepts JSON, never accepts Base64 via argv -
    fails closed on wrong length/type/read failure. The key bytes are
    never logged, printed, or included in any exception message this
    function raises."""
    try:
        with open(path, "rb") as handle:
            raw = handle.read()
    except OSError as exc:
        raise IssuerError(f"failed to read private key file {path!r}: {exc.__class__.__name__}") from None
    if len(raw) != PRIVATE_KEY_RAW_BYTES:
        raise IssuerError(f"private key file {path!r} must contain exactly {PRIVATE_KEY_RAW_BYTES} raw bytes, found {len(raw)}")
    try:
        return Ed25519PrivateKey.from_private_bytes(raw)
    except ValueError:
        raise IssuerError(f"private key file {path!r} does not contain a valid Ed25519 private key") from None
    finally:
        raw = None  # best-effort - CPython bytes are immutable, but drop the reference promptly


def _resolve_ancestors(path: str):
    current = os.path.abspath(path)
    while True:
        yield current
        parent = os.path.dirname(current)
        if parent == current:
            return
        current = parent


def _refuse_if_inside_git_repo(path: str) -> None:
    """Best-effort, reliable-enough detection: refuses an output path if
    ANY ancestor directory (starting from the path's own parent) contains
    a `.git` entry. This is NOT a security boundary against a determined
    operator, only a guardrail against an accidental `--private-key-out`/
    `--out` inside a git working tree - see module docs."""
    directory = os.path.dirname(os.path.abspath(path)) or "."
    for ancestor in _resolve_ancestors(directory):
        if os.path.exists(os.path.join(ancestor, ".git")):
            raise IssuerError(
                f"refusing to write {path!r}: {ancestor!r} is (or is inside) a git repository - "
                "choose an output path outside any git working tree"
            )


def _refuse_if_exists(path: str) -> None:
    if os.path.exists(path):
        raise IssuerError(f"refusing to overwrite existing file: {path!r}")


def _atomic_write_secret_file(path: str, data: bytes) -> None:
    """Same discipline as gateway/api/activations.py's _atomic_write_store:
    write to a sibling temp file (mode 0600 from the start via os.open),
    fsync, os.replace, fsync the containing directory. Never a partial or
    best-effort write; never overwrites an existing file (checked by the
    caller before this is invoked, and enforced again here via O_EXCL on
    the FINAL path through the rename target check)."""
    directory = os.path.dirname(os.path.abspath(path)) or "."
    os.makedirs(directory, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".activation-envelope-issuer.", suffix=".tmp")
    try:
        try:
            os.chmod(tmp_path, 0o600)
        except OSError:
            # Windows: os.chmod's owner-write bit is a poor analogue of
            # POSIX 0600 and provides no group/other ACL guarantee - see
            # module/docs' own truthful platform-limitation note. Best
            # effort only; never treated as a security guarantee here.
            pass
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        if os.path.exists(path):
            raise IssuerError(f"refusing to overwrite existing file: {path!r}")
        os.replace(tmp_path, path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
    dir_fd = os.open(directory, os.O_RDONLY)
    try:
        os.fsync(dir_fd)
    finally:
        os.close(dir_fd)


# --- generate-key ---

def public_key_fingerprint_sha256_hex(public_key: Ed25519PublicKey) -> str:
    pub_bytes = public_key.public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)
    return hashlib.sha256(pub_bytes).hexdigest()


def public_key_base64(public_key: Ed25519PublicKey) -> str:
    pub_bytes = public_key.public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)
    return base64.b64encode(pub_bytes).decode("ascii")


def cmd_generate_key(args) -> int:
    _refuse_if_exists(args.private_key_out)
    _refuse_if_exists(args.public_metadata_out)
    _refuse_if_inside_git_repo(args.private_key_out)
    _refuse_if_inside_git_repo(args.public_metadata_out)

    private_key = Ed25519PrivateKey.generate()
    public_key = private_key.public_key()
    priv_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    try:
        _atomic_write_secret_file(args.private_key_out, priv_bytes)
    finally:
        priv_bytes = None

    fingerprint = public_key_fingerprint_sha256_hex(public_key)
    metadata = {
        "issuerKeyId": args.key_id,
        "publicKeyBase64": public_key_base64(public_key),
        "publicKeyFingerprintSha256Hex": fingerprint,
    }
    metadata_bytes = (json.dumps(metadata, indent=2) + "\n").encode("utf-8")
    _atomic_write_secret_file(args.public_metadata_out, metadata_bytes)

    print(f"activation_envelope_issuer: generated activation-issuer key id={args.key_id}")
    print(f"activation_envelope_issuer: public key fingerprint (sha256)={fingerprint}")
    print(f"activation_envelope_issuer: private key written to {args.private_key_out} (raw {PRIVATE_KEY_RAW_BYTES} bytes - "
          "KEEP OFFLINE, never commit, never transmit)")
    print(f"activation_envelope_issuer: public metadata written to {args.public_metadata_out}")
    if os.name == "nt":
        print(
            "activation_envelope_issuer: WARNING - this is a Windows filesystem; POSIX 0600 permissions "
            "were NOT applied (os.chmod's owner-write bit is not an ACL guarantee on Windows). Restrict "
            "access to this file's directory manually (e.g. NTFS ACLs) before leaving it on this machine.",
            file=sys.stderr,
        )
    return 0


# --- optional --bootstrap-bundle inspection (strict, read-only, non-trust) ---

def inspect_signed_manifest_bundle(path: str) -> Tuple[int, bytes]:
    """Strict, READ-ONLY inspection of an EXISTING SignedManifestCodec
    artifact (produced by gateway/tools/manifest_signing.py's
    sign-and-package command) - returns (manifest_version, sha256_of_exact_file_bytes).
    This is operator-side metadata inspection ONLY - it never re-signs,
    never becomes a trust decision, and never modifies manifest signing
    semantics. Validates the SAME outer-container shape SignedManifestCodec.decode
    (Kotlin) enforces - format version, canonical/signature length bounds,
    exact-container (no trailing bytes) - then reads only as much of the
    (already-validated-length) canonical prefix as needed to extract the
    manifest version, without parsing endpoints at all.

    Raises BundleInspectionError on ANY malformed/truncated/oversized
    input - never returns a partial result."""
    try:
        with open(path, "rb") as handle:
            raw = handle.read()
    except OSError as exc:
        raise BundleInspectionError(f"failed to read bootstrap bundle {path!r}: {exc.__class__.__name__}") from None

    offset = 0

    def _read_i32() -> int:
        nonlocal offset
        if offset + 4 > len(raw):
            raise BundleInspectionError("bootstrap bundle is truncated (expected a 4-byte length/version field)")
        value = struct.unpack_from(">i", raw, offset)[0]
        offset += 4
        return value

    outer_format_version = _read_i32()
    if outer_format_version != 1:
        raise BundleInspectionError(f"unsupported signed-manifest container format: {outer_format_version}")

    canonical_len = _read_i32()
    if canonical_len < 0 or canonical_len > _SIGNED_MANIFEST_MAX_CANONICAL_BYTES:
        raise BundleInspectionError(f"implausible canonical manifest length: {canonical_len}")
    if offset + canonical_len > len(raw):
        raise BundleInspectionError("bootstrap bundle is truncated (canonical section shorter than declared)")
    canonical_start = offset
    offset += canonical_len

    signature_len = _read_i32()
    if signature_len < 0 or signature_len > _SIGNED_MANIFEST_MAX_SIGNATURE_BYTES:
        raise BundleInspectionError(f"implausible signature length: {signature_len}")
    if offset + signature_len > len(raw):
        raise BundleInspectionError("bootstrap bundle is truncated (signature section shorter than declared)")
    offset += signature_len

    if offset != len(raw):
        raise BundleInspectionError(f"trailing bytes after signed-manifest container (expected EOF): {len(raw) - offset} extra byte(s)")

    # Only the canonical manifest's OWN format version + manifestVersion int
    # are read here - never endpoints. Mirrors ManifestCanonicalizer's field
    # order (FORMAT_VERSION, manifestVersion, ...) without duplicating its
    # full endpoint-parsing logic.
    if canonical_len < 8:
        raise BundleInspectionError("canonical manifest section too short to contain a format version and manifestVersion")
    manifest_canonical_format_version = struct.unpack_from(">i", raw, canonical_start)[0]
    if manifest_canonical_format_version != 1:
        raise BundleInspectionError(f"unsupported manifest canonical format version: {manifest_canonical_format_version}")
    manifest_version = struct.unpack_from(">i", raw, canonical_start + 4)[0]
    if manifest_version < 1:
        raise BundleInspectionError(f"implausible manifestVersion: {manifest_version}")

    # Hash the EXACT file bytes - never just the canonical section, never a
    # reserialized representation - see module docs.
    content_hash = hashlib.sha256(raw).digest()
    return manifest_version, content_hash


# --- endpoint hints (operator CLI argument parsing) ---

def _validate_hints_order_preserving(hints: Sequence[str]) -> Tuple[str, ...]:
    if len(hints) > MAX_ENDPOINT_HINTS:
        raise IssuerError(f"too many --endpoint-hint arguments ({len(hints)} > {MAX_ENDPOINT_HINTS})")
    if len(set(hints)) != len(hints):
        raise IssuerError("--endpoint-hint values must not contain a duplicate")
    for hint in hints:
        if not hint:
            raise IssuerError("--endpoint-hint must not be blank")
        hint_bytes = hint.encode("utf-8")
        if len(hint_bytes) > MAX_ENDPOINT_HINT_UTF8_BYTES:
            raise IssuerError(f"--endpoint-hint {hint!r} exceeds max UTF-8 byte length ({MAX_ENDPOINT_HINT_UTF8_BYTES}): {len(hint_bytes)}")
    return tuple(hints)  # ORIGINAL ORDER - never sorted/deduplicated-and-reordered


# --- issue ---

def cmd_issue(args) -> int:
    # Step 1-4: validate EVERY local/operator input BEFORE touching the
    # activation store - see module's atomicity requirement.
    if args.envelope_valid_for_hours <= 0 or args.envelope_valid_for_hours > 24 * 366:
        raise IssuerError(f"--envelope-valid-for-hours must be a positive, bounded number of hours (got {args.envelope_valid_for_hours})")

    private_key = read_private_key_file(args.private_key_file)
    public_key = private_key.public_key()

    _refuse_if_exists(args.out)
    _refuse_if_inside_git_repo(args.out)

    hints = _validate_hints_order_preserving(args.endpoint_hint or [])

    bundle_ref: Optional[BundleRef] = None
    if args.bootstrap_bundle:
        try:
            manifest_version, content_hash = inspect_signed_manifest_bundle(args.bootstrap_bundle)
        except BundleInspectionError as exc:
            raise IssuerError(f"--bootstrap-bundle rejected: {exc}") from None
        bundle_ref = BundleRef(manifest_version=manifest_version, content_hash=content_hash)

    if not args.issuer_key_id:
        raise IssuerError("--issuer-key-id must not be blank")

    # Step 5: only now call the EXISTING, unmodified issuance authority.
    activations_module = _activations_module()
    try:
        activation_id, credential = activations_module.issue_activation(
            args.store, args.lock, args.max_devices, args.activation_expires_in_days,
        )
    except (activations_module.ActivationStoreError, ValueError) as exc:
        raise IssuerError(f"issue_activation failed: {exc}") from None

    # Everything from here on MUST either succeed all the way through step
    # 9 (durable artifact write) or revoke the activation just created -
    # never leave a plaintext-credential activation ACTIVE with no
    # delivered envelope. See module's CRITICAL ATOMICITY requirement.
    try:
        issued_at = int(time.time() * 1000)
        not_before = issued_at
        requested_expires_at = issued_at + int(args.envelope_valid_for_hours * 3600 * 1000)

        server_expires_at = None
        record = activations_module.find_by_activation_id(args.store, args.lock, activation_id)
        if record is not None and record.get("expires_at"):
            from datetime import datetime

            server_expires_at = int(datetime.fromisoformat(record["expires_at"]).timestamp() * 1000)

        if server_expires_at is not None and requested_expires_at > server_expires_at:
            # FAIL LOUDLY rather than silently clamping - chosen over
            # silent clamping because every other explicit CLI input in
            # this tool (--envelope-valid-for-hours itself) is required,
            # never silently substituted; an operator who asked for a
            # longer envelope than the entitlement allows almost
            # certainly made a mistake worth surfacing, not quietly
            # correcting. See module docs / B56_ACTIVATION_ISSUER_KEY_CEREMONY.md.
            raise IssuerError(
                f"requested envelope lifetime (expiring at epoch millis {requested_expires_at}) would extend "
                f"beyond this activation's own server-side expiry (epoch millis {server_expires_at}) - "
                "reduce --envelope-valid-for-hours or issue a longer-lived activation"
            )
        expires_at = requested_expires_at

        envelope = ActivationEnvelope(
            activation_id=activation_id,
            credential=credential,
            issued_at_epoch_millis=issued_at,
            not_before_epoch_millis=not_before,
            expires_at_epoch_millis=expires_at,
            bootstrap_bundle_ref=bundle_ref,
            bootstrap_endpoint_hints=hints,
            bootstrap_capability_hint=None,
            nonce=secrets.token_bytes(NONCE_LENGTH),
            issuer_key_id=args.issuer_key_id,
        )

        canonical = canonical_bytes(envelope)
        signature = private_key.sign(canonical)
        artifact = pack_signed_envelope(canonical, signature)
        _atomic_write_secret_file(args.out, artifact)
        artifact_sha256 = hashlib.sha256(artifact).hexdigest()
    except BaseException as exc:
        _revoke_or_report_critical(args, activation_id, exc)
        return 1
    finally:
        credential = None  # best-effort - drop the local reference promptly

    print(f"activation_envelope_issuer: activation_id={activation_id} issuerKeyId={args.issuer_key_id}")
    print(f"activation_envelope_issuer: envelope issuedAt={issued_at} expiresAt={expires_at} max_devices={args.max_devices}")
    print(f"activation_envelope_issuer: issuer public key fingerprint (sha256)={public_key_fingerprint_sha256_hex(public_key)}")
    print(f"activation_envelope_issuer: envelope artifact written to {args.out} (sha256={artifact_sha256})")
    if bundle_ref is not None:
        print(f"activation_envelope_issuer: bootstrap bundle manifestVersion={bundle_ref.manifest_version} contentHash(sha256)={bundle_ref.content_hash.hex()}")
    return 0


def _revoke_or_report_critical(args, activation_id: str, original_exc: BaseException) -> None:
    """CRITICAL ATOMICITY - see module docs. Never prints the credential.
    Always non-zero exit; the caller (`cmd_issue`) already returns 1."""
    print(f"activation_envelope_issuer: ERROR - envelope creation/signing/output failed after activation "
          f"{activation_id} was created: {original_exc}", file=sys.stderr)
    try:
        _activations_module().revoke_activation(args.store, args.lock, activation_id)
    except Exception as revoke_exc:  # noqa: BLE001 - must never propagate a raw traceback here
        print(
            f"activation_envelope_issuer: CRITICAL - failed to auto-revoke activation_id={activation_id} "
            f"after the error above ({revoke_exc}). MANUAL REVOCATION REQUIRED: run "
            f"'activation_tokens.py --store {args.store} --lock {args.lock} revoke {activation_id}' now.",
            file=sys.stderr,
        )
        return
    print(
        f"activation_envelope_issuer: activation_id={activation_id} was automatically REVOKED "
        "because its envelope artifact was never successfully delivered.",
        file=sys.stderr,
    )


# --- CLI wiring ---

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="activation_envelope_issuer.py",
        description="B56-4A operator-only ActivationEnvelope issuer CLI (separate from activation_tokens.py)",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate-key", help="generate a new activation-issuer Ed25519 keypair (private key file-based only)")
    gen.add_argument("--key-id", required=True, help="the issuerKeyId this key will sign envelopes under")
    gen.add_argument("--private-key-out", required=True, help="output path for the raw 32-byte private key (refuses to overwrite)")
    gen.add_argument("--public-metadata-out", required=True, help="output path for public metadata JSON (issuerKeyId/publicKeyBase64/fingerprint - no private material)")

    issue = sub.add_parser("issue", help="issue a new activation and a signed ActivationEnvelope for it")
    issue.add_argument("--store", required=True, help="path to activations.json (same store activation_tokens.py uses)")
    issue.add_argument("--lock", help="path to the activation store lock file (default: <store>.lock)")
    issue.add_argument("--issuer-key-id", required=True, help="ActivationEnvelope.issuerKeyId - identifies which activation-issuer public key must verify this envelope")
    issue.add_argument("--private-key-file", required=True, help="path to a raw 32-byte Ed25519 private key file - NEVER pass the key itself on the command line")
    issue.add_argument("--max-devices", type=int, default=1, help="device limit for the new activation (default: 1)")
    issue.add_argument("--activation-expires-in-days", type=float, default=None, help="optional server-side activation entitlement expiry, in days from now")
    issue.add_argument("--envelope-valid-for-hours", type=float, required=True, help="REQUIRED - how long the signed envelope itself remains valid, in hours (architecture guidance: roughly 24-72h, not mandated)")
    issue.add_argument("--endpoint-hint", action="append", default=[], help="optional, repeatable, non-authoritative EndpointId hint (order preserved, max 32, no duplicates)")
    issue.add_argument("--bootstrap-bundle", default=None, help="optional path to an ALREADY-signed SignedManifestCodec artifact (from manifest_signing.py) to correlate by exact-byte SHA-256 + manifest version - never re-signed")
    issue.add_argument("--out", required=True, help="output path for the signed envelope artifact - SECRET (contains the plaintext activation credential); refuses to overwrite")

    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "issue" and not args.lock:
        args.lock = args.store + ".lock"
    try:
        if args.command == "generate-key":
            return cmd_generate_key(args)
        if args.command == "issue":
            return cmd_issue(args)
    except IssuerError as exc:
        print(f"activation_envelope_issuer: error: {exc}", file=sys.stderr)
        return 1
    return 1


if __name__ == "__main__":
    sys.exit(main())
