"""B46-4P.3 - renders the Hysteria2 SERVER config (apernet/hysteria
app/v2.12.3, pinned in gateway/hysteria/VERSION) from the SAME
POCVPN_API_HYSTERIA2_* settings /v1/hysteria-profile advertises to clients,
so the port/SNI a client is told and the port/cert the server actually
serves cannot drift apart.

Schema source (read, not guessed): app/cmd/server.go at commit
e1366b173ccf5706e1e4630fe8aa654a4b574085 - serverConfig.Listen, .TLS
{cert,key,sniGuard}, .Auth {type: http, http: {url, insecure}},
.Masquerade.Type ("404" = http.NotFoundHandler), .ACL.Inline
(extras/outbounds/acl grammar `outbound(address)`, evaluated AFTER the
resolver - Resolver(ACL(Outbounds)) - so a hostname resolving to a private
address is matched by its IP).

Invariants this module owns:
- The auth URL host is the literal "127.0.0.1" (same boundary as
  hysteria_auth_server._BIND_HOST); only its port is an input.
- No secret ever appears in the output: client credentials are checked by
  the loopback auth backend, TLS material is referenced by path only.
- No masquerade listenHTTP/listenHTTPS (TCP 80/443 belong to nginx).
- Client traffic may not reach loopback, link-local (incl. the EC2 metadata
  endpoint), private/VPC or other non-public ranges - otherwise any valid
  Hysteria2 credential would be a proxy into this host's own loopback
  services (the API on 8443-8446, the auth backend itself, Xray 2100).

Operator use (as pocvpn-api, on the gateway, after api.env is complete):
    cd /opt/pocvpn/gateway && python3 -m api.hysteria_server_config > config.yaml
Fails closed (non-zero, nothing on stdout) unless the whole Hysteria2 group
AND POCVPN_API_HYSTERIA2_AUTH_BACKEND_PORT are configured.
"""
import re
import sys

from . import config as config_module

AUTH_BACKEND_HOST = "127.0.0.1"
AUTH_BACKEND_PATH = "/auth"
# Runtime copies owned by the Hysteria2 user (see
# gateway/edge/nova-hysteria-cert-deploy-hook.sh) - never /etc/letsencrypt,
# whose private keys are root:root 0600.
TLS_CERT_PATH = "/etc/nova-hysteria/tls/fullchain.pem"
TLS_KEY_PATH = "/etc/nova-hysteria/tls/privkey.pem"

ACL_REJECT_CIDRS = (
    "0.0.0.0/8",
    "10.0.0.0/8",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
    "172.16.0.0/12",
    "192.0.0.0/24",
    "192.168.0.0/16",
    "198.18.0.0/15",
    "224.0.0.0/4",
    "240.0.0.0/4",
    "::/128",
    "::1/128",
    # NOT ::ffff:0:0/96: Go's net.IPNet.Contains normalizes that network to
    # 0.0.0.0/0, so it would reject EVERY IPv4 destination (verified with
    # go1.26). IPv4-mapped IPv6 addresses are already matched by the IPv4
    # ranges above (::ffff:127.0.0.1 is inside 127.0.0.0/8).
    "64:ff9b::/96",
    "fc00::/7",
    "fe80::/10",
    "ff00::/8",
)

_HOSTNAME_LABEL_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")


class HysteriaServerConfigError(ValueError):
    pass


def _check_port(name, value):
    if isinstance(value, bool) or not isinstance(value, int) or not (1 <= value <= 65535):
        raise HysteriaServerConfigError(f"{name} must be an integer in 1..65535, got {value!r}")


def _check_sni(sni):
    """A DNS hostname only: an IP literal cannot be sent as TLS SNI, and the
    certificate is matched with sniGuard: strict."""
    if not isinstance(sni, str) or not sni or len(sni) > 253 or sni != sni.lower():
        raise HysteriaServerConfigError(f"SNI must be a lower-case DNS hostname, got {sni!r}")
    labels = sni.split(".")
    if len(labels) < 2 or not all(_HOSTNAME_LABEL_RE.match(label) for label in labels):
        raise HysteriaServerConfigError(f"SNI must be a lower-case DNS hostname, got {sni!r}")
    if labels[-1].isdigit():
        raise HysteriaServerConfigError(f"SNI must be a DNS hostname, not an IP address: {sni!r}")


def render_server_config(server_port, sni, auth_backend_port):
    _check_port("server_port", server_port)
    _check_port("auth_backend_port", auth_backend_port)
    _check_sni(sni)
    acl_lines = "".join(f"    - reject({cidr})\n" for cidr in ACL_REJECT_CIDRS)
    return (
        "# Generated by gateway/api/hysteria_server_config.py (B46-4P.3) - do not hand-edit.\n"
        "# Hysteria2 server, schema of apernet/hysteria app/v2.12.3 (gateway/hysteria/VERSION).\n"
        f"# Advertised SNI: {sni} (POCVPN_API_HYSTERIA2_SNI). The certificate below is the\n"
        "# runtime copy of that hostname's Let's Encrypt lineage, maintained by\n"
        "# gateway/edge/nova-hysteria-cert-deploy-hook.sh. Contains no secrets.\n"
        f'listen: ":{server_port}"\n'
        "tls:\n"
        f"  cert: {TLS_CERT_PATH}\n"
        f"  key: {TLS_KEY_PATH}\n"
        "  sniGuard: strict\n"
        "auth:\n"
        "  type: http\n"
        "  http:\n"
        f'    url: "http://{AUTH_BACKEND_HOST}:{auth_backend_port}{AUTH_BACKEND_PATH}"\n'
        "    insecure: false\n"
        "masquerade:\n"
        '  type: "404"\n'
        "acl:\n"
        "  inline:\n"
        f"{acl_lines}"
        "    - direct(all)\n"
    )


def render_from_app_config(app_config):
    if not (
        app_config.hysteria2_store_path
        and app_config.hysteria2_lock_path
        and app_config.hysteria2_server_port
        and app_config.hysteria2_sni
    ):
        raise HysteriaServerConfigError("Hysteria2 group (POCVPN_API_HYSTERIA2_*) is not configured")
    if not app_config.hysteria2_auth_backend_port:
        raise HysteriaServerConfigError("POCVPN_API_HYSTERIA2_AUTH_BACKEND_PORT is not configured")
    return render_server_config(
        app_config.hysteria2_server_port, app_config.hysteria2_sni, app_config.hysteria2_auth_backend_port,
    )


def main():
    try:
        text = render_from_app_config(config_module.load_config())
    except (config_module.ConfigError, HysteriaServerConfigError) as exc:
        print(f"hysteria_server_config: {exc}", file=sys.stderr)
        raise SystemExit(1)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
